"""
Opisy zwierząt po angielsku — wejście dla generatora grafik.

Baza trzyma tylko nazwy polskie, a model po polsku myli gatunki. Źródłem prawdy
jest tu POLSKA nazwa z `animals.ts`, nie `id` — kilka identyfikatorów wprowadza
w błąd:

  binturong_indo  -> „Niedźwiedź pszczelarz" to biruang, nie binturong
  asp             -> „Boleń" to ryba, nie żmija
  bison           -> „Żubr" to żubr europejski; bizon ma własne `bison_american`
  bird_eater      -> „Ptasznik" to pająk ptasznik
  basilisk        -> bazyliszek płatkogłowy (jaszczurka), nie stwór z mitów
  finch           -> „Zięba" to zięba zwyczajna, nie dowolna łuszczakowata
  hawk            -> „Jastrząb" to jastrząb gołębiarz, nie jakikolwiek myszołów
  isopod_giant    -> „Rajak głębinowy" to ten sam stonóg morski co `giant_isopod`
                     (ciekawostka w bazie mówi wprost „morski stonóg"), więc
                     opisy różnią się tylko barwą
  komodo_juvenile -> młody waran z Komodo; dorosły siedzi w `komodo`
  monarch_butterfly    -> „Cytrynek" to szczeżuja/latolistek (Gonepteryx rhamni),
                          nie motyl monarcha (ten siedzi pod `monarch`)
  morpho_blue           -> „Modraszek ariom" to Duży Modraszek (Phengaris arion),
                          mały niebieski motyl w czarne kropki, nie modrasz morpho
  sun_spider            -> „Topik" to pająk topik (Argyroneta aquatica), żyjący
                          pod wodą w bańce powietrza — nie pająk słoneczny/wielbłądzi
  mantis_shrimp_punching -> „Krab bokser" to zupełnie inne zwierzę niż krewetka
                          modliszkowa — mały krab trzymający ukwiały w szczypcach
  vampire_squid_giant   -> „Kalmar Humboldta" to agresywny czerwonawy kałamarnica,
                          nie wampirzyca głębinowa (ta jest pod `vampire_squid`)

Każdy opis dokłada 1–2 cechy rozpoznawcze, bo dziecko ma odróżnić gatunki,
a nie tylko zobaczyć „jakieś słodkie zwierzę".

Gdy branch `fix/animal-data` podmienił gatunek pod istniejącym `id` (np.
`axolotl_pink` z aksolotla na żabę moczarową), opis MUSI pójść za nową polską
nazwą — inaczej rysunek pokazuje co innego niż podpis.

Opisy owadów i pająków trzeba trzymać łagodnie: „army ant soldier with very
large curved jaws" i „brown recluse ... violin shape" odbiły się od filtru
bezpieczeństwa modelu. Wystarczyło opisać kształt zamiast nazywać groźny
gatunek — zwroty były bezpłatne, ale zadanie przepada.
"""

DESCRIPTIONS: dict[str, str] = {
    # --- partia 1 (wygenerowana) ---
    "aardvark": "an aardvark, with its long snout, long ears and arched back",
    "aardvark_pig": "a babirusa, a wild pig with sparse grey bristles and long curved tusks that grow upward through the snout",
    "aardwolf": "an aardwolf, a small striped hyena-like animal with a bushy mane and pointed ears",
    "aardwolf_kenya": "a striped hyena, grey-brown with black leg stripes, a long shaggy mane along the back and large pointed ears",
    "addax": "an addax antelope, white coat with a brown forehead patch and long spiral horns",
    "adelie_penguin": "an Adelie penguin, black head with a white ring around the eye",
    "african_wild_dog": "an African wild dog, with big round ears and a patchy brown, black and white coat",
    "agouti": "an agouti, a large rodent with a rounded body, slim legs and glossy brown fur",
    "albatross": "an albatross, a large white seabird with very long narrow wings and a hooked pale beak",
    "alligator": "an alligator, with a broad rounded snout and bumpy dark green scales",

    # --- partia 2 ---
    "alligator_snapping": "an alligator snapping turtle, with a spiky ridged shell and a strongly hooked beak",
    "alpaca": "an alpaca, with a woolly fleece, long neck and a shaggy fringe over the eyes",
    "amphipod_giant": "a giant amphipod, a pale shrimp-like crustacean with a curved segmented body",
    "anaconda": "a green anaconda, a very thick olive-green snake with dark oval blotches",
    "anchovy": "an anchovy, a small slender silver fish with a bright lateral stripe",
    "angelfish": "a freshwater angelfish, a tall flat triangular fish with long trailing fins and vertical stripes",
    "angler_fish": "a deep-sea anglerfish, dark round body, huge toothy mouth and a glowing lure on its head",
    "anole": "a green anole lizard, slender and bright green with a pink throat fan",
    "ant": "a black garden ant, with a narrow waist, six legs and bent antennae",
    "anteater": "a giant anteater, with a very long tube snout, bushy striped tail and a dark shoulder stripe",
    "antelope": "an impala antelope, sandy coat, white belly and long lyre-shaped horns",
    "aphid": "an aphid, a tiny pear-shaped green insect on a leaf",
    "arapaima": "an arapaima, a huge elongated river fish with large red-edged scales",
    "arctic_fox": "an arctic fox in white winter coat, with small rounded ears and a very bushy tail",
    "arctic_tern": "an arctic tern, a slim white seabird with a black cap, red beak and forked tail",
    "arctic_wolf": "an arctic wolf, thick white fur, broad head and amber eyes",
    "argali": "an argali wild sheep, with enormous curling horns and a pale neck ruff",
    "armadillo": "a nine-banded armadillo, with a segmented bony shell and a long thin tail",
    "army_ant": "a reddish-brown ant with a slender segmented body, bent antennae and six thin legs",
    "arowana": "an arowana, a long silver fish with big shining scales and two barbels on the chin",
    "asian_elephant": "an Asian elephant, smaller rounded ears, arched back and a domed head",
    "asian_hornet": "an Asian hornet, dark body with a yellow band and orange face",
    "asp": "an asp fish, a slim silvery predatory river fish with a pointed jutting lower jaw",
    "atlantic_puffin": "a razorbill, a black and white seabird with a deep blunt black beak crossed by a thin white line",
    "atlas_butterfly": "a Queen Alexandra's birdwing butterfly, very large with long narrow wings in iridescent blue-green and a bright yellow body",
    "atlas_moth": "a big friendly cartoon moth with soft furry body and wide patterned wings in warm brown and cream",
    "atolla_jellyfish": "an Atolla jellyfish, a deep red bell with many trailing tentacles and one long one",
    "avocet": "a pied avocet, white with black markings, long blue legs and a thin upcurved beak",
    "axolotl": "an axolotl, pale pink with feathery external gills and a wide smiling face",
    "axolotl_pink": "a moor frog, a small brown frog with a dark eye patch and a pale stripe down the back",
    "aye_aye": "an aye-aye, a lemur with huge round eyes, enormous ears and one very long thin finger",
    "badger": "a European badger, stocky grey body with bold black and white face stripes",
    "bald_eagle": "a bald eagle, white head and tail, dark brown body and a large yellow hooked beak",
    "bandicoot": "a bandicoot, a small marsupial with a pointed snout, big ears and coarse brown fur",
    "banteng": "a banteng, wild cattle with white stockings, a white rump patch and curved horns",
    "barn_owl": "a barn owl, with a white heart-shaped face and golden speckled wings",
    "barnacle": "a cluster of acorn barnacles, pale cone-shaped shells on a rock",
    "barracuda": "a barracuda, long silver torpedo-shaped fish with a jutting jaw and sharp teeth",
    "barreleye": "a barreleye fish, a small deep-sea fish with a transparent dome head and tubular green eyes",
    "basilisk": "a plumed basilisk lizard, bright green with a tall crest on head and back",
    "bat": "a small brown bat hanging, with wide membrane wings and big rounded ears",
    "beaded_lizard": "a Mexican beaded lizard, stout black body covered in yellow bead-like scales",
    "bearded_seal": "a bearded seal, plump grey body with very long white whiskers",
    "beaver": "a beaver, with a stocky brown body, orange front teeth and a flat scaly tail",
    "bee": "a honeybee, golden and black striped fuzzy body with translucent wings",
    "bee_eater": "a European bee-eater, turquoise belly, chestnut back, yellow throat and a long curved beak",
    "beetle": "a stag beetle, glossy dark brown with large antler-like jaws",
    "beluga": "a beluga whale, all white with a rounded forehead melon and no dorsal fin",
    "betta": "a betta fish, deep blue and red with huge flowing veil fins",
    "bharal": "a bharal blue sheep, blue-grey coat with black flank stripes and short curved horns",
    "bigfoot": "a friendly bigfoot, a tall shaggy brown ape-like creature with big feet",
    "bilby": "a bilby, a small marsupial with very long rabbit-like ears and a black-and-white tail",
    "binturong": "a binturong, a shaggy black bearcat with tufted ears and a long prehensile tail",
    "binturong_indo": "a masked palm civet, slender grey-brown with a bold white facial stripe from forehead to nose and a long tail",
    "bird_eater": "a Goliath birdeater tarantula, a very large hairy brown spider",
    "bird_of_paradise": "a bird of paradise, with brilliant yellow and orange plumes and long wire tail feathers",
    "bison": "a European bison, a massive brown wisent with a high shoulder hump and short curved horns",
    "bison_american": "an American bison, huge shaggy brown head and shoulders with a beard",
    "black_widow": "a black widow spider, glossy black with a red hourglass on the abdomen",
    "black_woodpecker": "a black woodpecker, all black with a bright red crown and pale eye",
    "blackbird": "a common blackbird, glossy black plumage with an orange-yellow beak and eye ring",
    "blobfish": "a blobfish, a pale pink gelatinous deep-sea fish with a droopy nose and sad face",
    "blue_crab": "a blue crab, with bright blue claws and a wide flattened olive shell",
    "blue_morpho": "a blue morpho butterfly with brilliant iridescent blue wings spread open",
    "blue_whale_pygmy": "a pygmy blue whale, a slender blue-grey whale with a small dorsal fin far back",
    "boa": "a boa constrictor, a thick tan snake with dark brown saddle-shaped markings",
    "bombardier_beetle": "a bombardier beetle, orange head and legs with a blue-black abdomen",
    "bongo": "a bongo antelope, chestnut red with bold white vertical stripes and spiral horns",
    "booby": "a blue-footed booby, a white and brown seabird with vivid bright blue feet",
    "bowerbird": "a satin bowerbird, glossy blue-black with violet eyes, beside a stick bower",
    "bowhead": "a bowhead whale, a stocky black whale with a huge arched jaw and white chin patch",
    "box_jellyfish": "a box jellyfish, a transparent cube-shaped bell with long trailing tentacles",
    "brachiosaurus": "a friendly brachiosaurus, a long-necked dinosaur with front legs longer than the back",
    "bream": "a common bream, a deep flat-bodied bronze fish with small head",
    "brittle_star": "a brittle star, with a small central disc and five long thin flexible arms",
    "brook_trout": "a huchen, a very large elongated salmon with a coppery-brown back and small dark spots",
    "brown_bear": "a brown bear, heavy build with a shoulder hump and small round ears",
    "brown_recluse": "a cute cartoon spider with a round light-brown body, big friendly eyes and eight slender legs",
    "budgerigar": "a budgerigar, a small green and yellow parrot with black barring and a blue cere",
    "buffalo": "an African buffalo, black with heavy horns joined in a boss across the forehead",
    "bull_shark": "a bull shark, stocky grey shark with a short blunt rounded snout",
    "bullfinch": "a Eurasian bullfinch, a plump bird with a rosy red breast, black cap and grey back",
    "bullfrog": "an American bullfrog, large olive-green frog with a big round eardrum",
    "bumblebee": "a bumblebee, very fuzzy round body with black and yellow bands",
    "burbot": "a burbot, a long mottled brown freshwater cod with a single chin barbel",
    "bush_dog": "a bush dog, small stocky reddish-brown wild dog with short legs and small ears",
    "bushmaster": "a bushmaster snake, large tan pit viper with dark diamond markings",
    "butterfly": "a butterfly with open patterned orange and black wings",
    "butterflyfish": "a butterflyfish, a round yellow and white reef fish with a black eye stripe",
    "buzzard": "a common buzzard, a broad-winged brown hawk with a pale chest band",
    "caecilian": "a caecilian, a legless burrowing amphibian that looks like a large smooth ringed worm",
    "caiman": "a spectacled caiman, olive-green with a bony ridge between the eyes",
    "camel_spider": "a camel spider, a pale tan solifuge with very large forward-facing jaws",
    "canary": "a canary, a small bright yellow songbird with a conical beak",
    "candiru": "a candiru, a tiny translucent pale catfish with a slender eel-like body",
    "cane_toad": "a cane toad, a very large warty brown toad with big poison glands behind the eyes",
    "capybara": "a capybara, the largest rodent, barrel-shaped with a blunt square muzzle",
    "caracal": "a caracal, a tawny wild cat with very long black ear tufts",
    "caribou": "a caribou reindeer, with broad branching antlers and a pale neck mane",
    "carp": "a common carp, a stocky golden-bronze fish with large scales and two pairs of barbels",

    # --- partia 3 ---
    "carpenter_ant": "a large black carpenter ant with a shiny segmented body and bent antennae",
    "cassowary": "a cassowary, a big flightless bird with a tall bony helmet, blue neck and red wattles",
    "cassowary_dwarf": "a dwarf cassowary, smaller with a low helmet and bright blue bare neck",
    "cat": "a domestic cat sitting, with upright ears, round eyes and a curled tail",
    "caterpillar": "a plump green caterpillar with soft segments and tiny legs on a leaf",
    "catfish": "a wels catfish, a long smooth dark fish with a wide flat head and long barbels",
    "catfish_polish": "a barbel fish, a slim golden-brown river fish with a rounded snout and four chin barbels",
    "centipede": "a centipede, a long flat reddish-brown body with many pairs of thin legs",
    "chameleon": "a chameleon, green with a curled tail, bulging swivel eyes and a crested head",
    "chamois": "a chamois, a goat-antelope with a pale face, black eye stripes and short hooked horns",
    "cheetah": "a cheetah, slender tan cat with solid round black spots and black tear lines down the face",
    "chicken": "a hen, plump brown body with a small red comb and wattles",
    "chimpanzee": "a chimpanzee sitting, dark fur with a pale face and big expressive ears",
    "chinchilla": "a chinchilla, very soft grey fur, round ears and a bushy tail",
    "chinstrap_penguin": "a chinstrap penguin, white face with a thin black line under the chin",
    "chipmunk": "a chipmunk, small striped rodent with bold dark and cream stripes along its back",
    "chub": "a chub, a stocky silver river fish with large scales and a broad blunt head",
    "cicada": "a cicada, a broad-headed insect with clear veined wings held roof-like over the body",
    "cicada_periodical": "a periodical cicada with a black body, bright red eyes and orange wing veins",
    "clam": "a clam with a pale ridged two-part shell, slightly open",
    "cleaner_shrimp": "a cleaner shrimp, translucent with bold red and white stripes and long white antennae",
    "clouded_leopard": "a clouded leopard, grey-gold cat with large cloud-shaped blotches and a very long tail",
    "clownfish": "a clownfish, bright orange with three white bands edged in black",
    "coati": "a coati, brown with a long upturned snout and a ringed tail held upright",
    "cobra": "a cobra rearing up with its hood spread wide",
    "cockatoo": "a sulphur-crested cockatoo, white with a bright yellow crest raised",
    "cockroach": "a cockroach, a flat oval glossy brown insect with long thin antennae",
    "cockroach_asian": "a slender light-brown roach with long antennae and pale wing covers",
    "coconut_crab": "a coconut crab, a huge land crab with thick blue-purple claws and sturdy legs",
    "cod": "an Atlantic cod, olive-brown speckled fish with a pale lateral line and a chin barbel",
    "coelacanth": "a coelacanth, a heavy blue fish with white flecks and thick lobed fins",
    "comb_jelly": "a comb jelly, a transparent oval jelly with shimmering rainbow comb rows",
    "condor": "an Andean condor, black with a white neck ruff and a bare pink head",
    "cone_snail": "a cone snail with a smooth glossy cone-shaped shell patterned in brown and cream",
    "copperhead": "a copperhead snake, coppery tan with darker hourglass bands",
    "coral": "a branching coral colony in warm orange and pink",
    "coral_snake": "a coral snake with bold red, yellow and black rings",
    "cormorant": "a cormorant standing with wings spread, glossy black with a hooked beak",
    "cow": "a dairy cow, white with black patches, a pink muzzle and a small udder",
    "coyote": "a coyote, slender grey-tan wild dog with large pointed ears and a bushy tail",
    "crab": "a crab with a rounded red shell, two big claws and stalked eyes",
    "crab_japanese_spider": "a Japanese spider crab with an orange body and extremely long thin legs",
    "crab_spider": "a crab spider, a small pale spider with wide front legs held sideways like a crab",
    "crane_grey": "a common crane, tall grey bird with a red crown patch and a white cheek stripe",
    "crayfish": "a crayfish, a small freshwater lobster with brown-red shell and raised claws",
    "crested_gecko": "a crested gecko, warm orange with fringed crests over the eyes and no eyelids",
    "cricket": "a cricket, a brown insect with long hind legs and very long thin antennae",
    "cricket_house": "a house cricket, pale straw-brown with dark head bands and long antennae",
    "crocodile": "a crocodile with a narrow V-shaped snout and visible teeth along the jawline",
    "crossbill": "a crossbill, a red finch whose beak tips cross over each other",
    "crow": "a crow, all black with a stout beak and glossy feathers",
    "crown_of_thorns_starfish": "a crown-of-thorns starfish, a large purple-red star covered in spines",
    "crowned_crane": "a grey crowned crane with a golden spray crest, white cheeks and a red throat pouch",
    "crucian": "a crucian carp, a deep-bodied golden-bronze fish with a rounded back",
    "cuckoo": "a common cuckoo, slim grey bird with a barred white belly and a long tail",
    "cuttlefish": "a cuttlefish with a broad flat body, W-shaped pupils and a fringe fin all around",
    "cuttlefish_giant": "a giant cuttlefish, large and iridescent with wavy arms and a wide fin fringe",
    "damselfly": "a damselfly, very slender with a bright blue body and wings folded along the back",
    "darwin_frog": "a Darwin's frog, small green-brown frog with a pointed nose like a leaf tip",
    "deathstalker": "a pale yellow scorpion with slender pincers and a thin curved tail",
    "deer": "a red deer stag, russet coat with tall branching antlers",
    "dhole": "a dhole, a reddish Asian wild dog with a bushy black-tipped tail and rounded ears",
    "dik_dik": "a dik-dik, a tiny antelope with huge dark eyes and a long flexible snout",
    "dingo": "a dingo, a sandy-ginger wild dog with erect ears and a bushy tail",
    "discus": "a discus fish, a very round flat fish with swirling blue and orange patterns",
    "dog": "a friendly dog sitting, with floppy ears and a wagging tail",
    "dolphin": "a bottlenose dolphin leaping, grey with a curved dorsal fin and a smiling beak",
    "donkey": "a donkey, grey with very long ears and a dark shoulder stripe",
    "dormouse": "an edible dormouse, soft grey fur, big black eyes and a bushy squirrel-like tail",
    "dormouse_garden": "a garden dormouse, brown above and white below with a black bandit mask",
    "dragon": "a friendly cartoon dragon, green scales, small wings and a curled tail",
    "dragonfish": "a deep-sea dragonfish, long dark eel-like body with a glowing barbel on the chin",
    "dragonfly": "a dragonfly with a slim iridescent blue body and four clear outstretched wings",
    "duck": "a mallard duck, green head, white neck ring and a yellow bill",
    "dugong": "a dugong, a plump grey sea cow with a broad downturned snout and a whale-like tail",
    "duiker": "a duiker, a small forest antelope with a rounded back and short straight horns",
    "dumbo_octopus": "a Dumbo octopus, pale pink with two big ear-like fins above the eyes",
    "dung_beetle": "a dung beetle, glossy black and round, rolling a small ball",
    "dungeness_crab": "a Dungeness crab with a wide purple-brown shell and pale-tipped claws",
    "eagle": "a golden eagle, dark brown with a golden nape and a large hooked beak",
    "eagle_owl": "a Eurasian eagle-owl, large tawny owl with orange eyes and prominent ear tufts",
    "eagle_owl_white": "a long-eared owl, slim grey-brown owl with very long ear tufts and orange eyes",
    "earthworm": "an earthworm, a smooth pink segmented worm with a pale band",
    "earwig": "an earwig, a slim brown insect with small pincers at the tail end",
    "echidna": "an echidna, a round spiny anteater with a long thin beak and cream spines",
    "eel": "a European eel, a long smooth snake-like fish with a continuous fin along the back",
    "eel_electric": "an electric eel, a long dark grey-brown fish with a flat head and orange throat",
    "eland": "a common eland, a very large tan antelope with a dewlap and straight spiral horns",
    "electric_ray": "an electric ray, a round flat brown ray with a short thick tail",
    "elephant": "an African elephant, very large ears, a long trunk and curved tusks",
    "elephant_seal": "an elephant seal, a huge grey seal with an inflatable trunk-like nose",
    "elk": "a moose, dark brown with a long drooping muzzle, a dewlap and broad flat antlers",
    "emperor_scorpion": "a large glossy black scorpion with thick pincers and a curved tail",
    "emu": "an emu, a tall shaggy brown flightless bird with a slim blue-grey neck",
    "european_hamster": "a European hamster, stocky with a black belly, white patches and small ears",
    "european_mink": "a European mink, sleek dark brown with a white chin and upper lip",
    "fairy_wren": "a superb fairywren, a tiny bird with a brilliant blue cap and cheeks and a cocked tail",
    "falcon": "a peregrine falcon, slate-grey back, barred white chest and a dark moustache mark",
    "feather_star": "a feather star, a crinoid with many feathery orange arms spread out",
    "fennec": "a fennec fox, tiny pale sandy fox with enormous ears",
    # --- partia 4 ---
    "ferret": "a domestic ferret, long slender cream body with a dark bandit mask and dark feet",
    "field_mouse": "a wood mouse, sandy-brown with a white belly, huge round ears and a long thin tail",
    "finch": "a common chaffinch, a small bird with a blue-grey cap, pinkish cheeks and two white wing bars",
    "fire_belly_toad": "an oriental fire-bellied toad, bumpy green and black back with a bright orange-and-black belly",
    "fire_salamander": "a fire salamander, glossy black with bold yellow blotches and a rounded head",
    "firefly": "a firefly beetle, a small brown beetle with a soft glowing yellow-green tip on its abdomen",
    "fishing_cat": "a fishing cat, a stocky olive-grey wild cat with dark spots in rows and a short thick tail",
    "flamingo": "a greater flamingo, tall pink bird on one leg with a long curved neck and a black-tipped bent bill",
    "flatworm": "a marine flatworm, a flat ribbon-like creature with ruffled edges and bright orange and blue stripes",
    "flea": "a flea, a tiny rounded brown insect with a smooth arched shell and long springy back legs",
    "flounder": "a flounder, a flat oval fish lying sideways with both eyes on one speckled brown side",
    "fly": "a housefly, a small grey insect with big round red eyes and two clear wings",
    "flying_fish": "a flying fish, a slim silvery fish with enormous wing-like pectoral fins spread out",
    "flying_squirrel": "a flying squirrel, grey-brown with huge black eyes and a skin flap stretched between its legs",
    "fossa": "a fossa, a slender rust-brown cat-like animal from Madagascar with a very long tail and a short muzzle",
    "fox": "a red fox, orange-red fur with a white chest, black legs and a bushy white-tipped tail",
    "frigatebird": "a great frigatebird, a black seabird with long pointed wings, a forked tail and a red throat pouch",
    "frilled_lizard": "a frilled lizard, sandy-brown with a wide round collar of skin fanned out around its head",
    "frog": "a common frog, a plump green-brown frog with golden eyes and long folded back legs",
    "frogfish": "a frogfish, a round lumpy yellow-orange fish with a tiny fishing rod on its forehead and leg-like fins",
    "funnel_web_spider": "a cute cartoon spider with a round glossy dark body, short sturdy legs and a small shiny head",
    "gaboon_viper": "a Gaboon viper, a thick short snake with a broad triangular head and a beautiful leaf-pattern of tan, brown and cream",
    "galago": "a bushbaby, a tiny grey primate with enormous round eyes, big thin ears and a long fluffy tail",
    "galapagos_tortoise": "a Galapagos giant tortoise, a huge domed grey shell, thick elephant-like legs and a long wrinkled neck",
    "gannet": "a northern gannet, a white seabird with a golden-buff head, black wingtips and a long pointed blue-grey bill",
    "garter_snake": "a garter snake, a slim smooth snake with three yellow stripes running along a dark olive body",
    "gaur": "a gaur, a massive dark brown wild ox with white stockings and a high ridge along its shoulders",
    "gazelle": "a Thomson's gazelle, tan with a bold black side stripe, white belly and slender ringed horns",
    "gecko": "a leopard gecko, a plump yellow lizard with black spots, a fat banded tail and a smiling face",
    "genet": "a common genet, a slender spotted grey cat-like animal with a very long black-and-white ringed tail",
    "gentoo_penguin": "a gentoo penguin, black and white with a wide white bonnet stripe over the eyes and an orange bill",
    "gerbil": "a Mongolian gerbil, sandy-brown with a white belly, large dark eyes and a tufted tail tip",
    "gharial": "a gharial, a slim crocodile with a very long narrow snout and a round bulb on the tip",
    "ghost_shark": "a chimaera or ghost shark, a pale silvery fish with huge green eyes, smooth skin and a long thin tail",
    "giant_anteater": "a tamandua, a small tree anteater with a golden coat and a bold black vest marking over the shoulders",
    "giant_centipede": "a giant centipede, a long reddish segmented body with many small orange legs along each side",
    "giant_isopod": "a giant isopod, a pale cream armoured sea bug with overlapping plates and large dark eyes",
    "giant_otter": "a giant otter, a long chocolate-brown otter with a cream throat patch and a wide flat paddle tail",
    "giant_salamander": "a giant salamander, a large flat wrinkled brown amphibian with tiny eyes and a broad rounded head",
    "giant_squid": "a giant squid, a long pale pink torpedo body with two huge eyes, eight arms and two longer tentacles",
    "giant_weta": "a giant weta, a large plump brown cricket-like insect with long antennae and thick spiny back legs",
    "gibbon": "a gibbon, a slim black-and-cream ape with extremely long arms and a pale face ring",
    "gila_monster": "a Gila monster, a chunky lizard with bumpy bead-like black and orange-pink skin and a fat tail",
    "giraffe": "a giraffe, a very long neck, tan coat with brown patches and two small furry horns",
    "glass_frog": "a glass frog, a tiny lime-green frog with see-through belly skin and big round eyes",
    "glass_octopus": "a glass octopus, an almost transparent octopus with visible tube-shaped eyes and thin clear arms",
    "gnu": "a blue wildebeest, a slate-grey ox-like antelope with a shaggy beard, curved horns and a dark mane",
    "goat": "a domestic goat, white with a short beard, backward-curving horns and rectangular pupils",
    "goblin_shark": "a goblin shark, a pale pink shark with a long flat blade-shaped snout and a slim body",
    "goldcrest": "a goldcrest, a tiny olive-green bird with a bright yellow crown stripe and a plump round body",
    "goldfinch": "a European goldfinch, a small bird with a red face, black-and-white head and a broad yellow wing bar",
    "goliath_beetle": "a Goliath beetle, a very large beetle with bold black-and-white striped back plates and reddish wing cases",
    "goose": "a greylag goose, a grey-brown goose with an orange bill and pink legs",
    "gorilla": "a mountain gorilla, a big black ape with a broad chest, a domed head and a silver-grey back",
    "gourami": "a pearl gourami, a flat oval fish with a pearly spotted body and very long thin feeler fins",
    "grass_snake": "a grass snake, a slim olive-green snake with a yellow-and-black collar behind the head",
    "grasshopper": "a grasshopper, a slim green insect with long folded jumping legs and short antennae",
    "gray_whale": "a gray whale, a mottled grey whale with a knobbly back ridge instead of a fin and pale barnacle patches",
    "grayling": "a grayling fish, a silvery fish with a very tall sail-like dorsal fin and a small pointed head",
    "great_grey_owl": "a great grey owl, a large grey owl with a huge round face of grey rings and small yellow eyes",
    "great_tit": "a great tit, a small bird with a black head, white cheeks, yellow breast and a black belly stripe",
    "great_white": "a great white shark, a grey torpedo-shaped shark with a white belly, a pointed snout and a tall triangular fin",
    "grebe": "a little grebe, a small round brown water bird with a chestnut neck and a fluffy tail-less rear",
    "grebe_great": "a great crested grebe, a slim white-necked water bird with a black crest and chestnut ruffs on the cheeks",
    "green_anaconda": "an emerald tree boa, bright green with white zigzag bars, coiled in loops over a branch",
    "griffin": "a friendly cartoon griffin, an eagle head and wings on a golden lion body with a tufted tail",
    "grizzly": "a grizzly bear, a big brown bear with a humped shoulder, a dished face and thick shaggy fur",
    "grouper": "a grouper, a big-bodied fish with a large mouth, thick lips and a mottled brown and pale pattern",
    "guanaco": "a guanaco, a slim tan llama-like animal with a grey face, white belly and large pointed ears",
    "guinea_fowl": "a helmeted guineafowl, a round dark grey bird covered in white dots with a bare blue head and a bony helmet",
    "guinea_pig": "a guinea pig, a plump tailless rodent with short legs and a brown-and-white patchy coat",
    "gulper_eel": "a gulper eel, a dark eel with an enormous pouch-like mouth and a very thin whip tail",
    "guppy": "a guppy, a tiny fish with a silver body and a large colourful orange and blue fan tail",
    "hagfish": "a hagfish, a long smooth grey-pink eel-like fish with no jaws and short barbels around the mouth",
    "halibut": "a halibut, a very large flat diamond-shaped fish with both eyes on its dark brown upper side",
    "hammerhead": "a hammerhead shark, a grey shark with a wide flat hammer-shaped head and an eye at each end",
    "hamster": "a Syrian hamster, a round golden-brown rodent with puffed cheek pouches and tiny ears",
    "hare": "a brown hare, long black-tipped ears, long powerful back legs and a lean tawny body",
    "harpy_eagle": "a harpy eagle, a big grey-and-white eagle with a black chest band and a crown of raised feathers",
    "harvestman": "a harvestman, a cute cartoon creature with one small round body and eight very long thin legs",
    "hawfinch": "a hawfinch, a stocky orange-brown finch with a huge silver-grey conical bill and a short white-tipped tail",
    "hawk": "a northern goshawk, a grey-backed hawk with finely barred white underparts and a bold white eyebrow stripe",
    "hawksbill_turtle": "a hawksbill sea turtle, an amber shell with overlapping patterned plates and a narrow pointed beak",
    "hedgehog": "a hedgehog, a round animal covered in brown-and-cream spines with a small pointed brown face",
    "hellbender": "a hellbender salamander, a big flat wrinkled brown amphibian with frilly skin folds along its sides",
    "hercules_beetle": "a Hercules beetle, a large beetle with olive-yellow wing cases and one long curved horn above its head",
    "hermit_crab": "a hermit crab, a small crab peeking out of a spiral seashell with one bigger orange claw",
    "heron": "a grey heron, a tall grey wading bird with a long S-shaped neck, a dagger bill and a black head plume",
    "herring": "a herring, a slim silvery-blue fish with a deeply forked tail and large round scales",
    "herring_gull": "a herring gull, a white gull with pale grey wings, black wingtips and a yellow bill with a red spot",
    "hippo": "a hippopotamus, a huge barrel-shaped grey animal with a very wide mouth and tiny ears",
    "hoatzin": "a hoatzin, a brown bird with a spiky ragged crest, a bare blue face and red eyes",
    "hobby": "a Eurasian hobby, a small slim falcon with a dark moustache mark, streaked chest and rusty-red trousers",
    "honey_badger": "a zorilla, a small striped polecat, black with four bold white stripes along the back and a bushy tail",
    "honey_possum": "a honey possum, a tiny brown mouse-like marsupial with three dark back stripes and a long pointed snout",
    "honeypot_ant": "a honeypot ant, a reddish-brown ant with a slender segmented body and a big round amber abdomen",
    "hoopoe": "a hoopoe, a sandy-pink bird with a tall fan-shaped orange crest and black-and-white striped wings",
    "hornbill": "a great hornbill, a big black-and-white bird with a huge curved yellow bill topped by a casque",
    "horned_lizard": "a horned lizard, a flat round sandy lizard with a crown of small blunt spikes around its head",
    "hornet": "a European hornet, a large gentle wasp with a brown-and-yellow striped body and clear wings",
    "horse": "a horse, a chestnut-brown horse with a flowing dark mane and tail and white socks",
    "horseshoe_crab": "a horseshoe crab, a smooth brown helmet-shaped shell with a long straight spike tail",
    "hummingbird": "a ruby-throated hummingbird, a tiny emerald-green bird with a red throat and a long thin bill, wings blurred",
    "humpback": "a humpback whale, a dark whale with very long white flippers and a knobbly bumpy head",
    "huntsman_spider": "a cute cartoon spider with a flat light-brown body and long sideways-spread legs, friendly and round-eyed",
    "hyena": "a spotted hyena, a sandy coat with dark round spots, a sloping back and large rounded ears",
    "ibex": "an Alpine ibex, a sturdy grey-brown mountain goat with enormous ridged curved-back horns",
    "ibis": "a sacred ibis, a white bird with a bare black head and neck and a long curved black bill",
    "iguana": "a green iguana, a bright green lizard with a spiny crest along its back and a round cheek scale",
    "impala": "an impala, a slender reddish antelope with a white belly, black rump stripes and long lyre-shaped horns",
    "indri": "an indri, a black-and-white lemur with a round green-eyed face, tufted ears and almost no tail",
    "isopod_giant": "a common woodlouse, a small grey segmented land crustacean with many short legs",
    "jackal": "a golden jackal, a slim sandy-gold wild dog with pointed ears and a black-tipped bushy tail",
    "jackdaw": "a jackdaw, a small black crow with a silver-grey nape and pale blue-white eyes",
    "jackson_chameleon": "a Jackson's chameleon, a green chameleon with three forward-pointing horns and curled tail",
    "jaguar": "a jaguar, a stocky golden cat with large rosette spots that have dots inside and a broad heavy head",
    "jaguarundi": "a jaguarundi, a small plain grey-brown cat with a long low body, short legs and a very long tail",
    "japanese_macaque": "a Japanese macaque, a thick grey-brown furred monkey with a bright red bare face and a short tail",
    "jay": "a Eurasian jay, a pinkish-brown bird with a bright blue barred wing patch and a black moustache stripe",
    "jellyfish": "a moon jellyfish, a translucent pale blue bell with four ring shapes inside and thin trailing tentacles",
    "jewel_beetle": "a jewel beetle, a torpedo-shaped beetle with shining metallic green wing cases and copper stripes",
    "jewel_beetle_emerald": "an emerald jewel beetle, a rounded beetle glowing bright emerald green with golden edges",
    "jumping_spider": "a cute cartoon jumping spider with a fuzzy round body and two very large friendly front eyes",
    "kakapo": "a kakapo, a big round moss-green parrot with mottled feathers, an owl-like face disc and a pale bill",
    "kangaroo": "a red kangaroo, a reddish-brown kangaroo with huge back legs, small arms and a thick tapered tail",
    "kea": "a kea, an olive-green mountain parrot with orange under its wings and a long curved grey bill",
    "kestrel": "a common kestrel, a small falcon with a rusty-red spotted back, grey head and a black-banded tail",
    "king_cobra": "a king cobra, an olive-brown snake rearing up with a narrow hood spread behind its head",
    "king_crab": "a red king crab, a spiny orange-red crab with a bumpy triangular shell and very long thin legs",
    "king_penguin": "a king penguin, black and white with bright orange teardrop ear patches and an orange bill stripe",
    "kingfisher": "a common kingfisher, a tiny bird with a brilliant blue back, orange chest and a long straight black bill",
    "kiwi": "a kiwi, a round shaggy brown flightless bird with no visible wings and a very long pale bill",
    "klipspringer": "a klipspringer, a small olive-speckled antelope standing on tiptoe hooves with short spike horns",
    "koala": "a koala, a grey round bear-like animal with huge fluffy ears and a large black spoon-shaped nose",
    "koi": "a koi carp, a plump fish with bold white, orange and black patches and flowing fins",
    "komodo": "a Komodo dragon, a very large grey-brown lizard with loose scaly skin, a long tail and sturdy legs",
    "komodo_juvenile": "a water monitor lizard, dark grey-brown with rows of pale yellow spots and a long banded tail",
    "kookaburra": "a laughing kookaburra, a chunky brown-and-cream kingfisher with a dark eye stripe and a huge bill",
    "kraken": "a friendly cartoon kraken, a big purple sea monster with curling tentacles and large round eyes",
    "krill": "a krill, a tiny transparent pink shrimp-like creature with big black eyes and feathery legs",
    "kudu": "a greater kudu, a grey-brown antelope with thin white side stripes and long corkscrew horns",
    "lacewing": "a green lacewing, a delicate pale green insect with golden eyes and large transparent net-veined wings",
    "ladybug": "a ladybird beetle, a round red beetle with seven black dots and a small black-and-white head",
    "langouste": "a spiny lobster, a reddish-brown lobster with no big claws, a spiny shell and very long thick antennae",
    "langur": "a grey langur, a slim monkey with silver-grey fur, a black face and a very long arching tail",
    "lanternfish": "a lanternfish, a small silvery-blue deep-sea fish with rows of tiny glowing dots along its belly",
    "lark": "a skylark, a streaky brown bird with a small pointed crest and white outer tail feathers",
    "leafcutter_ant": "a leafcutter ant, a reddish-brown ant with a slender segmented body carrying a green leaf piece",
    "leatherback_turtle": "a leatherback sea turtle, a huge dark rubbery shell with seven long ridges and very long front flippers",
    "lemming": "a Norway lemming, a small plump rodent with bold black, orange and cream patched fur and tiny ears",

    # --- partia 15 (kolejnych 200) ---
    "rabbit": "a domestic rabbit, soft brown fur, long upright ears and a round fluffy tail",
    "rat": "a fancy pet rat, sleek grey-brown fur, a long scaly pink tail and small round ears",
    "mouse": "a small house mouse, grey-brown fur, big round ears and a long thin tail",
    "sheep": "a domestic sheep, thick curly white wool, a pink bare face and short legs",
    "pig": "a pink domestic pig, a round body, curly tail and a flat snout",
    "rooster": "a farm rooster, glossy dark green-black tail feathers, a red comb and red wattle",
    "wolf": "a grey wolf, thick grey-brown fur, a bushy tail and amber eyes",
    "roe_deer": "a roe deer, slender reddish-tan coat, a white rump patch and small forked antlers",
    "wild_boar": "a wild boar, bristly dark brown fur, a heavy front-loaded body and short tusks",
    "lynx": "a Eurasian lynx, spotted tawny fur, tufted black ear tips and a short stubby tail",
    "marten": "a pine marten, slim brown body, a bushy tail and a pale creamy throat patch",
    "otter": "a Eurasian otter, sleek brown fur, a long tapered tail and small rounded ears",
    "squirrel": "a red squirrel, reddish fur, a big bushy tail and tufted ear tips",
    "stoat": "a stoat, slim orange-brown body with a white belly and a black-tipped tail",
    "weasel": "a least weasel, a tiny slender orange-brown body with a white belly and no black tail tip",
    "mole": "a European mole, velvety black-grey fur, tiny eyes and large spade-shaped front paws",
    "lion": "a male lion, tawny golden fur, a huge shaggy mane and a tufted tail",
    "zebra": "a plains zebra, bold black and white stripes covering its whole body",
    "leopard": "a leopard, tawny gold fur covered in dark rosette spots and a long spotted tail",
    "rhino": "a white rhinoceros, thick grey wrinkled skin, a wide square lip and two horns on its snout",
    "meerkat": "a meerkat, slim sandy-brown body, a dark eye mask and standing upright on its hind legs",
    "lemur": "a ring-tailed lemur, grey body, white face with dark eye patches and a long black-and-white ringed tail",
    "mandrill": "a mandrill, olive-brown fur with a bright red and blue ridged muzzle and a golden beard",
    "warthog": "a warthog, grey bristly skin, large curved tusks and wart-like bumps on its face",
    "tiger": "a tiger, orange fur with bold black stripes and a white belly",
    "panda": "a giant panda, round white body with black patches over the eyes, ears, legs and shoulders",
    "orangutan": "an orangutan, shaggy long reddish-orange fur and a wide flat face",
    "sloth": "a three-toed sloth, shaggy grey-brown fur, a round face and long curved claws",
    "macaque": "a Japanese macaque, thick beige-grey fur and a bare pink face",
    "ocelot": "an ocelot, tawny fur covered in dark chain-like rosettes and stripes",
    "platypus": "a platypus, a flat rubbery duck-like bill, brown otter-like fur and webbed feet",
    "porcupine": "a crested porcupine, a stocky dark body covered in long black-and-white banded quills",
    "polar_bear": "a polar bear, thick creamy-white fur, a long neck and a black nose",
    "walrus": "a walrus, wrinkled brown-pink skin, thick whiskers and two long ivory tusks",
    "seal": "a harbour seal, sleek silver-grey fur covered in dark spots and big round eyes",
    "reindeer": "a reindeer, thick brown fur, a white neck and large branching antlers",
    "musk_ox": "a musk ox, a very long shaggy dark brown coat reaching the ground and thick curved horns",
    "snowy_owl": "a snowy owl, mostly pure white feathers with a few dark speckles and bright yellow eyes",
    "whale": "a blue whale, a huge sleek blue-grey body with a small dorsal fin far back and pale mottling",
    "orca": "an orca, glossy black body with white eye patches, a white belly and a tall dorsal fin",
    "manatee": "a manatee, a large plump grey body with a wrinkled snout and a broad paddle-shaped tail",
    "narwhal": "a narwhal, a grey mottled whale with a single long spiralled ivory tusk",
    "sperm_whale": "a sperm whale, a huge dark grey whale with a massive block-shaped head and a wrinkled body",
    "porpoise": "a harbour porpoise, a small dark grey whale with a blunt rounded snout and a small triangular fin",
    "stork": "a white stork, white body with black wing feathers and long red legs and beak",
    "swallow": "a barn swallow, glossy blue-black back, a rusty-red throat and long forked tail streamers",
    "tit": "a blue tit, a bright blue cap and wings, yellow belly and white cheeks",
    "sparrow": "a house sparrow, streaky brown back, grey cap and a black bib under the beak",
    "pigeon": "a city pigeon, blue-grey body with a glossy green-purple neck sheen and two dark wing bars",
    "raven": "a common raven, all-black glossy feathers, a thick heavy beak and a shaggy throat",
    "magpie": "a Eurasian magpie, bold black and white plumage with a glossy blue-green sheen and a long tail",
    "nightingale": "a nightingale, a plain warm brown bird with a reddish-brown tail and large dark eyes",
    "woodpecker": "a great spotted woodpecker, black and white body with a bright red patch under the tail",
    "swan": "a mute swan, all-white plumage, a long curved neck and an orange bill with a black knob",
    "owl": "a tawny owl, mottled brown feathers, a round facial disc and large dark eyes",
    "vulture": "a griffon vulture, broad brown wings, a pale bald head and a ruff of downy feathers at the neck",
    "toucan": "a toco toucan, glossy black body, a white throat and a huge orange bill",
    "ostrich": "an ostrich, a huge flightless bird with fluffy black-and-white feathers, a long bare neck and pink legs",
    "peacock": "a peacock, an iridescent blue neck and chest with a huge fan of green-gold eye-spotted tail feathers",
    "parrot": "an African grey parrot, smooth grey feathers, a white face patch and a bright red tail",
    "pelican": "a great white pelican, white plumage, a very long flat bill and a large stretchy throat pouch",
    "penguin_emperor": "an emperor penguin, black back, white belly and bright orange-yellow patches on the neck",
    "penguin_little": "a little penguin, a small penguin with slate-blue back feathers and a white belly",
    "pike": "a northern pike, a long torpedo-shaped olive-green body with pale mottling and a flat duck-like snout",
    "salmon": "an Atlantic salmon, a streamlined silver fish with small dark X-shaped spots along its back",
    "trout": "a brown trout, an olive-brown fish covered in dark and red spots each ringed with pale halos",
    "tench": "a tench, a stocky olive-green fish with small scales, rounded fins and a tiny reddish eye",
    "perch": "a European perch, a golden-green fish with dark vertical stripes and bright orange-red fins",
    "zander": "a zander, an elongated silvery-grey fish with faint dark vertical bars and a sharp pointed head",
    "roach": "a roach fish, a silver deep-bodied fish with a small head, red eyes and reddish fins",
    "shark": "a great white shark, a grey torpedo-shaped body, a white belly and a tall triangular dorsal fin",
    "manta": "a manta ray, a huge flat black-and-white diamond-shaped body with wing-like fins and two horn-shaped head fins",
    "tuna": "a bluefin tuna, a thick streamlined dark blue-and-silver fish with a crescent tail and small yellow finlets",
    "mackerel": "an Atlantic mackerel, a slender silver fish with dark wavy stripes along its blue-green back",
    "swordfish": "a swordfish, a large blue-grey fish with a long flat sword-like bill and a tall dorsal fin",
    "seahorse": "a seahorse, an upright curled body with a horse-like head, a curled tail and a ridged back",
    "moray": "a moray eel, a long thick mottled brown-and-cream body with no fins and an open toothy mouth",
    "piranha": "a red-bellied piranha, a deep-bodied silvery fish with a bright red-orange belly and a sharp jaw",
    "snake": "a grass snake, a slender olive-green snake with a pale yellow-and-black collar behind the head",
    "python": "a Burmese python, a thick heavy-bodied tan snake covered in dark brown blotches",
    "rattlesnake": "a rattlesnake, a thick tan snake with dark diamond patterns and a segmented rattle at the tail tip",
    "lizard": "a sand lizard, a small green-and-brown lizard with a row of dark eye-spots along its sides",
    "sea_turtle": "a green sea turtle, a smooth olive-brown shell and large paddle-shaped flippers",
    "turtle": "a Hermann's tortoise, a high domed yellow-and-brown patterned shell and short stumpy legs",
    "toad": "a common toad, a squat warty grey-brown body with short legs and golden eyes",
    "salamander": "a fire salamander, a glossy black body with bold irregular bright yellow spots and patches",
    "newt": "a smooth newt, a slender brown-grey body with a spotted orange belly and a smooth wavy tail",
    "wasp": "a common wasp, a slender body with bold yellow and black bands and a narrow waist",
    "mosquito": "a mosquito, a tiny slender insect with long thin legs, clear wings and a fine pointed proboscis",
    "mayfly": "a mayfly, a delicate insect with clear net-veined wings held upright and long thin tail filaments",
    "moth": "a fuzzy grey moth with feathery antennae and patterned wings folded flat over its back",
    "mantis": "a praying mantis, a slender bright green body with a triangular head and large folded front legs",
    "stick_insect": "a stick insect, a very long thin brown-green body and legs that look just like a twig",
    "stag_beetle": "a male stag beetle, a glossy dark reddish-brown beetle with huge antler-shaped jaws",
    "termite": "a worker termite, a small pale soft-bodied insect with a rounded head and short legs",
    "spider": "a garden cross spider, a round brown abdomen marked with a pale cross of dots, on eight legs",
    "scorpion": "a scorpion, a segmented tan body with two large front pincers and a curled tail arched over its back",
    "tarantula": "a friendly fuzzy tarantula, a big round hairy brown body and eight thick furry legs",
    "tick": "a tick, a tiny flat oval body on eight small legs",
    "shrimp": "a shrimp, a curved translucent pink segmented body with long thin antennae and a fanned tail",
    "lobster": "a European lobster, a dark blue-black armoured body with two large front claws and a segmented tail",
    "snail": "a garden snail, a soft grey-brown body with two long eye stalks and a coiled brown-striped shell",
    "octopus": "an octopus, a bulbous rounded head and eight long suckered arms",
    "squid": "a squid, a smooth torpedo-shaped body with small side fins and two long tentacles among eight arms",
    "starfish": "a starfish, an orange body with five thick bumpy tapering arms",
    "seahorse_dwarf": "a tiny dwarf seahorse, a pale cream curled body with a horse-like head and a coiled tail",
    "turkey": "a wild turkey, a plump dark-feathered body with an iridescent sheen, a bare blue-red head and a fanned tail",
    "mule": "a mule, a sturdy horse-shaped body with long donkey-like ears and a short-maned neck",
    "llama": "a llama, a long-necked woolly body with a banana-shaped ear pair and a soft fringed face",
    "yak": "a yak, a stocky body covered in very long shaggy dark brown fur and long curved horns",
    "shrew": "a common shrew, a tiny reddish-brown velvety body with a long pointed twitching nose",
    "mountain_hare": "a mountain hare, a stocky body with pure white winter fur and black-tipped ears",
    "partridge": "a grey partridge, a round grey-brown bird with an orange face and a dark horseshoe mark on its belly",
    "pheasant": "a common pheasant, a coppery red patterned body, a long barred tail and a green head with red face wattles",
    "thrush": "a song thrush, a warm brown back and a cream breast covered in dark arrow-shaped spots",
    "mazurek": "a Eurasian tree sparrow, a brown cap, white cheeks with a bold black spot, and a small black bib",
    "mallard": "a male mallard duck, a glossy green head, a yellow bill, a white neck ring and a chestnut breast",
    "viper": "a common European adder, a grey-brown snake with a bold dark zigzag stripe down its back",
    "slowworm": "a slow worm, a smooth glossy coppery-bronze legless lizard with a snake-like body",
    "mongoose": "a mongoose, a slender grizzled grey-brown body, short legs and a long tapering tail",
    "oryx": "an oryx, a white antelope with bold black facial markings, black leg stripes and long straight horns",
    "springbok": "a springbok, a tan antelope with a white belly, a dark brown side stripe and a white flap on its rump",
    "rock_hyrax": "a rock hyrax, a small round-bodied brown-grey animal with short legs, tiny rounded ears and no visible tail",
    "serval": "a serval, a slender tall-legged golden cat covered in bold black spots, with very large rounded ears",
    "siberian_tiger": "a Siberian tiger, a very large pale orange tiger with thick fur and widely spaced black stripes",
    "red_panda": "a red panda, rusty-red fur, a long ringed bushy tail and white markings around the face",
    "sun_bear": "a sun bear, short sleek black fur and a pale orange crescent patch on its chest",
    "moon_bear": "an Asian black bear, shaggy black fur with a pale cream V-shaped crescent mark on its chest",
    "sloth_bear": "a sloth bear, shaggy long black fur, a pale snout and a cream V-shaped mark on its chest",
    "snow_leopard": "a snow leopard, thick pale grey-white fur covered in dark rosettes and a very long thick tail",
    "puma": "a puma, a sleek plain sandy-tan cat with a long thick tail and no spots",
    "raccoon": "a raccoon, grey fur, a black face mask around the eyes and a bushy tail with dark rings",
    "opossum": "a Virginia opossum, grey shaggy fur, a long pointed pink snout and a bare pink prehensile tail",
    "tasmanian_devil": "a Tasmanian devil, a stocky black-furred body with a white chest band and a pink snout",
    "wombat": "a wombat, a stocky round-bodied brown animal with short legs and a big flat head",
    "quokka": "a quokka, a small round-bodied brown wallaby with a rounded face and a wide friendly smile",
    "puffin": "an Atlantic puffin, a black and white seabird with a broad triangular bill striped orange, blue-grey and yellow",
    "whale_shark": "a whale shark, a huge grey-blue body covered in pale spots and stripes in a checkerboard pattern",
    "marlin": "a blue marlin, a long streamlined blue-black fish with a spear-like bill and a tall pointed dorsal fin",
    "moonfish": "an opah, a large round flat silvery fish covered in white spots with bright red fins and a red mouth",
    "sardine": "a sardine, a small slender silvery fish with a row of dark spots along its side",
    "sturgeon": "a sturgeon, a long tan-grey fish with rows of bony armoured plates along its back and sides and a pointed snout with barbels",
    "starling": "a common starling, glossy black feathers speckled with iridescent purple-green and white spots",
    "rhea": "a rhea, a large flightless grey-brown bird with a long neck, fluffy loose feathers and no tail",
    "white_eagle": "a white-tailed eagle, a dark brown body, a pale head and a bright white wedge-shaped tail",
    "osprey": "an osprey, a white head with a dark eye stripe, a brown back and long angled wings",
    "sparrowhawk": "a Eurasian sparrowhawk, a small hawk with a blue-grey back and orange-barred underparts",
    "macaw": "a scarlet macaw, a brilliant red body with blue and yellow wing feathers and a bare white face",
    "parakeet": "a cockatiel, a grey body with a tall yellow crest and a round orange cheek patch",
    "marabou": "a marabou stork, a huge grey-backed bird with a bald pink head, a massive bill and a pink dangling throat pouch",
    "saltwater_croc": "a saltwater crocodile, a huge dark grey-green body with bony ridged scales and a long powerful snout",
    "tortoise_giant": "a giant tortoise, an enormous high-domed brown shell and thick elephant-like legs",
    "monitor_lizard": "a desert monitor lizard, a long sandy-brown body covered in pale spots, with a long forked tongue",
    "poison_frog": "a poison dart frog, a tiny frog in vivid blue and black patches",
    "tree_frog": "a red-eyed tree frog, a bright green body, huge red eyes, orange feet and blue-striped sides",
    "louse": "a tiny pale greyish-tan wingless insect, a flat oval body with no spots or markings, six short legs ending in tiny hooked claws, no wings",
    "locust": "a locust, a stout yellow-brown grasshopper-like insect with long folded hind legs",
    "silk_moth": "a domestic silk moth, a plump white fuzzy-bodied moth with small pale wings",
    "mite": "a tiny mite, a very small round pale oval body with eight tiny legs",
    "slug": "a garden slug, a soft elongated orange-brown body with two small eye stalks and no shell",
    "oyster": "an oyster, a rough ruffled grey-white two-part shell slightly open",
    "sea_urchin": "a sea urchin, a round purple ball covered in long thin spines",
    "sea_anemone": "a sea anemone, a soft cylindrical stalk topped with a ring of waving pastel tentacles",
    "wildcat": "a European wildcat, a thick grey-brown tabby-striped cat with a bushy tail ringed in black with a blunt black tip",
    "vole": "a bank vole, a small round rodent with reddish-brown fur, a grey belly and a short tail",
    "water_shrew": "a water shrew, a small dark velvety-black shrew with a pointed nose and a fringe of stiff hairs on its feet",
    "polecat": "a European polecat, dark brown fur with a pale creamy face mask around the eyes and muzzle",
    "sable": "a sable, a slim dark brown weasel-like animal with a bushy tail and rounded ears",
    "musk_rat": "a muskrat, a large brown rodent with dense fur and a long scaly tail flattened side to side",
    "marmot": "an alpine marmot, a stocky brown-grey rodent with short legs, small round ears and a bushy tail",
    "okapi": "an okapi, a dark chestnut-brown body with a giraffe-like face and bold black-and-white striped legs",
    "pangolin": "a pangolin, a body entirely covered in overlapping brown scales, curled with a long tapering tail",
    "ratel": "a honey badger, a black body with a broad grey-white stripe running from head to tail along its back",
    "sitatunga": "a sitatunga, a shaggy brown antelope with faint white stripes and spots and long splayed hooves",
    "zebra_grevyi": "a Grevy's zebra, very narrow close-set black stripes, large rounded ears and a white belly",
    "tapir": "a Malayan tapir, a black front half and legs with a bold white saddle over the back half, and a short trunk-like snout",
    "proboscis_monkey": "a proboscis monkey, reddish-brown fur, a pale round belly and an enormous long drooping nose",
    "serow": "a serow, a stocky goat-antelope with a shaggy dark grey-brown coat and short backward-curving horns",
    "takin": "a takin, a stocky animal with a golden shaggy coat, a large humped snout and thick curved horns",
    "musk_deer": "a musk deer, a hunched tan-brown body with large ears, no antlers and long fang-like tusks curving from the upper jaw",
    "saiga": "a saiga antelope, a pale tan body with an oddly large bulbous drooping nose and ridged horns",
    "maned_wolf": "a maned wolf, a fox-faced animal with very long slender legs, reddish-orange fur and a dark mane along its back",
    "paca": "a paca, a large stocky reddish-brown rodent with rows of pale white spots along its sides",
    "tamarin": "a golden lion tamarin, a small monkey with brilliant orange-gold fur and a thick lion-like mane around its face",
    "marmoset": "a common marmoset, a tiny monkey with grey-brown fur and long white ear tufts",
    "vicuna": "a vicuna, a slender long-necked animal with soft tan wool and a white chest and belly",
    "pampas_deer": "a pampas deer, a small reddish-tan deer with a pale throat and small forked antlers",
    "snowshoe_hare": "a snowshoe hare, a stocky white-furred hare with very large broad hind feet and black-tipped ears",
    "wolverine": "a wolverine, a stocky dark brown animal with a broad head and a pale tawny stripe along each side",
    "orca_killer": "a fin whale, a huge sleek grey-brown whale with a small curved dorsal fin set far back and a pale chevron marking behind the head",
    "right_whale": "a North Atlantic right whale, a huge stocky black whale with no dorsal fin and rough pale patches on its head",
    "sea_lion": "a sea lion, a sleek tan-brown body with small visible ear flaps and long flippers it can walk on",
    "leopard_seal": "a leopard seal, a long sleek grey body covered in dark spots and a very large reptilian-looking head",
    "siskin": "a Eurasian siskin, a small yellow-green finch with a black cap and black-streaked wings",
    "waxwing": "a Bohemian waxwing, a soft pinkish-brown crested bird with a black eye mask and bright red wax-like wingtips",
    "serin": "a European serin, a tiny finch with a bright yellow head and chest and a streaky olive back",
    "quetzal": "a resplendent quetzal, an iridescent emerald-green body, a bright red belly and very long trailing tail feathers",
    "toucan_keel": "a keel-billed toucan, a black body, a yellow chest and a huge bill striped in green, orange and red",
    "shoebill": "a shoebill, a tall grey stork-like bird with a huge bulbous shoe-shaped grey bill",

    # --- partia 3 (ostatnie 156, druga tura) ---
    "secretary_bird": "a secretary bird, a tall grey bird of prey with black quill-like crest feathers, an orange-red face patch, and very long crane-like legs",
    "rockhopper_penguin": "a rockhopper penguin, black and white with spiky yellow-and-black crest feathers above red eyes and an orange beak",
    "parrotfish": "a parrotfish, a chunky reef fish in blue and green with a fused beak-like mouth",
    "wrasse": "a wrasse, a slender elongated reef fish in blue and yellow with a pointed snout",
    "lionfish": "a lionfish, a reddish-white striped fish with dramatic fan-like feathery fins",
    "stonefish": "a stonefish, a warty grey-brown fish that looks like a lumpy rock, with an upturned mouth",
    "pufferfish": "a pufferfish, a round inflated grey-yellow fish with big eyes and a small beak",
    "porcupinefish": "a porcupinefish, a round inflated fish covered in stiff spines that stick outward",
    "mola_giant": "an ocean sunfish, a huge flat disc-shaped silver-grey fish with tall fins on top and bottom and no visible tail",
    "mamba": "a black mamba, a slender olive-grey snake with smooth scales and a narrow elongated head",
    "thorny_devil": "a thorny devil, a small tan desert lizard entirely covered in cone-shaped spines and two large spiky false horns on its head",
    "matamata": "a matamata turtle, a flat leaf-shaped brown shell with a long snake-like neck and a wide triangular head with star-shaped nose flaps",
    "softshell_turtle": "a softshell turtle, with a flat rubbery pancake-shaped shell, leathery skin instead of scutes, and a long snorkel-like nose",
    "mantella": "a golden mantella frog, a tiny frog in vivid orange-gold with smooth glossy skin",
    "rhinoceros_beetle": "a rhinoceros beetle, a large glossy dark brown beetle with a big curved horn on its head",
    "praying_mantis_giant": "a giant praying mantis, a slender green insect with an elongated body and folded front legs held up near its head",
    "walking_stick": "a leaf-green twig lying among branches that is actually a very long slender insect in disguise, with thin jointed legs",
    "monarch": "a monarch butterfly, bright orange wings with bold black veins and white spots along the edges",
    "treehopper": "a treehopper, a tiny insect with an odd helmet-shaped bump on its back that looks like a thorn",
    "whip_scorpion": "a vinegaroon, a flattened dark brown creature with large front pincers and a long thin tail whip, no stinger",
    "millipede": "a millipede, a long segmented brown-black body with many short legs in neat rows, curled slightly",
    "mantis_shrimp": "a mantis shrimp, a colorful shrimp-like crustacean in green and orange with large folded claws",
    "nautilus": "a nautilus, a spiral shell striped in cream and reddish-brown, with many small tentacles peeking out",
    "vampire_squid": "a vampire squid, a small dark red-black squid with webbed arms and large pale eyes",
    "sea_cucumber": "a sea cucumber, a soft elongated cucumber-shaped body in dull brown-orange lying on the seafloor",
    "sea_slug": "a sea slug, a soft rounded pink body with two small tentacles on its head, gliding on a rock",
    "mantis_shrimp_peacock": "a peacock mantis shrimp, a shrimp-like crustacean in brilliant green, orange, and blue with large club-like claws",
    "trex": "a Tyrannosaurus rex, a huge bipedal dinosaur with a massive head, tiny arms, and powerful legs",
    "velociraptor": "a velociraptor, a small feathered dinosaur about the size of a turkey, with a long tail and a curved sickle claw on each foot",
    "triceratops": "a triceratops, a sturdy dinosaur with three horns on its face and a wide bony frill around its neck",
    "stegosaurus": "a stegosaurus, a large dinosaur with a row of tall bony plates along its back and spikes on its tail",
    "mammoth": "a woolly mammoth, a huge shaggy brown-furred elephant-like creature with long curved tusks",
    "sabretooth": "a saber-toothed cat, a tawny muscular cat with two very long curved fangs hanging past its jaw",
    "unicorn": "a unicorn, a white horse with a flowing mane and tail and a single spiral horn on its forehead",
    "phoenix": "a phoenix, a mythical bird with brilliant fiery red, orange, and gold plumage and long trailing tail feathers, as if wreathed in flame",
    "mermaid": "a friendly cartoon mermaid character with long flowing hair and a shimmering scaled fish tail in place of legs, sitting on a rock by the sea",
    "yeti": "a yeti, a huge shaggy white-furred ape-like creature standing upright in the snow",
    "nessie": "the Loch Ness monster, a long-necked serpent-like creature with a humped dark green body rising out of lake water",
    "sphinx": "a sphinx, a mythical creature with the tawny furred body, paws, and tail of a lion, and a dignified face crowned with a striped headdress",
    "mole_eu": "a hazel dormouse, a tiny rodent with soft orange-brown fur, a long furry tail, and large round black eyes",
    "snow_fox": "an arctic hare, a large white-furred hare with long black-tipped ears and powerful hind legs",
    "snub_nosed_monkey": "a golden snub-nosed monkey, with long golden-orange fur, a bright blue bare face, and an upturned nose",
    "reindeer_svalbard": "a small stocky reindeer with thick brown-white fur, short legs, and branching antlers",
    "skunk": "a skunk, with glossy black fur and a bold white stripe running down its back, and a bushy tail",
    "saola": "a saola, a dark brown antelope-like animal with long straight parallel horns and white stripes on its face",
    "pichi": "a pichi armadillo, a small animal covered in bony brown armor plates with a short tail and strong digging claws",
    "lyrebird": "a lyrebird, a large brown ground bird with elaborate long tail feathers fanned out in a lyre shape",
    "moonjellyfish": "a moon jellyfish, a translucent white-blue circular jellyfish with four horseshoe-shaped markings visible through its bell",
    "octopus_blue_ring": "a blue-ringed octopus, a small yellowish-brown octopus covered in iridescent blue rings",
    "reticulated_python": "a reticulated python, a long tan-brown snake with a striking black and gold geometric net-like pattern",
    "peacock_butterfly": "a peacock butterfly, with reddish-brown wings marked by four large eye-spots",
    "numbat": "a numbat, a small reddish-brown marsupial with white stripes across its back, a long pointed snout, and a bushy tail",
    "wallaby": "a wallaby, a small grey-brown kangaroo-like marsupial with long hind legs and a thick tail",
    "tree_kangaroo": "a tree kangaroo, a reddish-brown furry marsupial with a long tail, climbing along a branch",
    "yapok": "a water opossum, a grey animal with bold black patches, webbed hind feet, and a long ringed tail",
    "tenrec": "a tenrec, a small spiny hedgehog-like mammal in brown-black with pale stripes running along its body",
    "sifaka": "a sifaka, a lemur with silky white fur, a dark face, and a very long tail",
    "tarsier": "a tarsier, a tiny primate with enormous round eyes, grey-brown fur, long thin fingers, and a long tail",
    "markhor": "a markhor, a wild goat with long dramatic corkscrew-spiral horns and a shaggy brown coat with a darker beard",
    "urial": "a urial, a wild sheep with a reddish-brown coat, a white belly, and curved ridged horns",
    "pallas_cat": "a Pallas's cat, a stocky grey cat with extremely dense long fur, a flattened round face, and low-set ears",
    "sand_cat": "a sand cat, a small sandy-tan cat with oversized ears and a black-ringed tail tip",
    "raccoon_dog": "a raccoon dog, a stocky dog-like animal with brown-grey fur, a dark facial mask, and a bushy tail",
    "peccary": "a collared peccary, a grey-black bristly pig-like animal with a pale band of fur around its neck and shoulders",
    "olingo": "an olingo, a slender brown arboreal mammal with a long banded tail and a pointed face",
    "margay": "a margay, a small wildcat with a tawny coat covered in dark rosettes and spots, and a very long tail",
    "spectacled_bear": "a spectacled bear, a black-furred bear with distinctive cream-white rings and patches around its eyes",
    "silky_anteater": "a silky anteater, a tiny anteater covered in soft golden fur, with a long curled prehensile tail",
    "mara": "a mara, a large rabbit-like rodent with long thin legs, grey-brown fur, and a pale rump patch",
    "viscacha": "a viscacha, a chinchilla-like rodent with soft grey fur, bold black-and-white facial markings, and a bushy tail",
    "prairie_dog": "a prairie dog, a small tan-brown ground squirrel-like rodent with a stout body and short tail",
    "solenodon": "a solenodon, a shrew-like mammal with a long flexible snout, dark brown fur, and a scaly tail",
    "sea_otter": "a sea otter, a brown furry marine mammal floating on its back with small paws held on its chest",
    "naked_mole_rat": "a naked mole rat, a small pink hairless wrinkled rodent with tiny eyes and large front teeth",
    "screech_owl": "a screech owl, a small mottled grey-brown owl with prominent pointed ear tufts and yellow eyes",
    "skua": "a skua, a stocky brown seabird with dark plumage and a strong hooked beak",
    "macaroni_penguin": "a penguin with a black back and white belly, and tall wavy golden-yellow feather plumes sweeping back above each eye",
    "mockingbird": "a mockingbird, a slender grey bird with a long tail and bold white patches on its wings",
    "motmot": "a motmot, a green-blue bird with a black facial mask and a long tail ending in two bare-shafted rackets",
    "roller": "a European roller, a bright blue bird with a cinnamon-brown back and wings",
    "sunbird": "a sunbird, a tiny iridescent green-and-purple bird with a long thin downcurved beak",
    "whooping_crane": "a whooping crane, a tall white crane with a red facial patch, black wingtips, and long legs and neck",
    "spoonbill": "a spoonbill, a white wading bird with a long flat spoon-shaped bill and long legs",
    "stilt": "a black-winged stilt, a black and white bird with extremely long thin pink legs",
    "oystercatcher": "an oystercatcher, a black and white bird with a long straight orange-red bill",
    "sandpiper": "a sandpiper, a small brown-mottled shorebird with short legs and a thin bill",
    "robin_european": "a European robin, a small plump brown bird with a bright orange-red breast and face",
    "wagtail": "a white wagtail, a slim grey-black-and-white bird with a long tail",
    "nuthatch": "a nuthatch, a small blue-grey bird with a black eye stripe and a short tail, gripping a tree trunk head-first",
    "treecreeper": "a treecreeper, a small brown streaky bird with a thin downcurved bill, climbing up a tree trunk",
    "nightjar": "a nightjar, a mottled grey-brown bird with a flat wide head, camouflaged like tree bark",
    "swift": "a swift, a dark sooty bird with long scythe-shaped wings and a forked tail",
    "rhea_lesser": "a lesser rhea, a large flightless bird with fluffy grey-brown feathers, a long neck, and no visible tail",
    "rudd": "a rudd, a silver freshwater fish with bright red-orange fins",
    "smelt": "a smelt, a small slender silvery translucent fish",
    "sterlet": "a sterlet, an elongated grey-tan fish with rows of bony plates along its body and a pointed snout with thin barbels",
    "tetra_neon": "a neon tetra, a tiny fish with a bright electric-blue stripe along its side and a red lower body",
    "mandarinfish": "a mandarinfish, a tiny fish with a wavy psychedelic pattern of blue, orange, and green",
    "triggerfish": "a triggerfish, an oval-bodied reef fish with a bold pattern and a small tight downturned mouth",
    "surgeonfish": "a surgeonfish, an oval flattened reef fish in blue-grey with a small pointed ridge near the base of its tail",
    "snapper": "a snapper, a silvery-pink elongated fish with a pointed head",
    "tiger_shark": "a tiger shark, a grey shark with dark vertical stripes along its body and a blunt rounded snout",
    "nurse_shark": "a nurse shark, a brownish-grey shark with a flattened body and two small barbels near its mouth",
    "mako_shark": "a mako shark, a sleek blue-grey shark with a pointed conical snout",
    "thresher_shark": "a thresher shark, a grey shark with an extremely long scythe-like upper tail lobe",
    "stingray": "a stingray, a flat diamond-shaped grey-brown ray with a long whip-like tail",
    "sawfish": "a sawfish, a shark-like ray with a long flat blade-shaped snout lined with teeth along both edges",
    "lungfish": "a lungfish, an elongated eel-like grey-brown fish with slender fleshy fins",
    "mudskipper": "a mudskipper, a small brown fish with bulging eyes on top of its head, propped up on strong front fins",
    "pacu": "a pacu, a round deep-bodied silvery fish with flat square teeth",
    "tigerfish": "an African tigerfish, a streamlined silvery predatory fish with a row of prominent pointed teeth",
    "luna_moth": "a luna moth, a pale mint-green moth with long trailing tails on its hindwings and small eyespots",
    "silkworm": "a silkworm caterpillar, a plump soft pale creamy-white caterpillar",
    "monarch_butterfly": "a brimstone butterfly, with pale sulphur-yellow leaf-shaped wings and no black markings",
    "swallowtail": "a swallowtail butterfly, with black and yellow patterned wings, long tail streamers on the hindwings, and small red-blue eyespots",
    "morpho_blue": "a large blue butterfly, small with vivid blue wings bordered in black and scattered dark spots",
    "mayfly_giant": "a giant mayfly, a delicate pale insect with lacy transparent wings and two long thin tail filaments",
    "water_strider": "a water strider, a slender insect with very long thin legs, resting on the surface of the water",
    "weevil": "a weevil, a small oval beetle with an elongated snout-like nose",
    "paper_wasp": "a paper wasp, a slender insect with a narrow waist and a yellow-and-brown banded abdomen",
    "tarantula_hawk": "a tarantula hawk wasp, with a shiny blue-black body and bright orange wings",
    "wolf_spider": "a wolf spider, a fuzzy brown ground spider with a compact body and thick legs",
    "orb_weaver": "a wasp spider, with a plump abdomen patterned in yellow-and-black stripes",
    "trapdoor_spider": "a trapdoor spider, a stocky brown spider with a smooth rounded abdomen",
    "peacock_spider": "a peacock spider, a tiny spider with a colorful fan-shaped flap on its abdomen patterned in blue, red, and orange",
    "whip_spider": "a whip spider, a flat-bodied creature with very long thin whip-like front legs and no tail",
    "sun_spider": "a small brown diving bell spider resting inside a silvery bubble of air underwater, surrounded by pondweed",
    "tiger_snake": "a tiger snake, a banded olive-and-yellow snake with smooth glossy scales",
    "sea_snake": "a sea snake, a slender snake with black-and-white bands and a flattened paddle-like tail",
    "sidewinder": "a sidewinder, a sandy-tan snake with small horn-like scales above each eye, coiled in an S-shape on sand",
    "milk_snake": "a milk snake, with bold bands of red, black, and pale yellow along its body",
    "skink": "a skink, a smooth glossy-scaled lizard with an elongated body and small short legs",
    "tuatara": "a tuatara, a lizard-like reptile with a row of soft spines along its back and olive-brown skin",
    "tokay_gecko": "a tokay gecko, a blue-grey gecko covered in orange spots, with large round eyes",
    "panther_chameleon": "a panther chameleon, in vivid patches of turquoise, red, and green, with a curled tail and bulging independent eyes",
    "loggerhead_turtle": "a loggerhead sea turtle, with a large head and a reddish-brown heart-shaped shell",
    "red_eared_slider": "a red-eared slider turtle, with a green shell and a bright red stripe behind each eye",
    "painted_turtle": "a painted turtle, with a smooth dark shell edged in red and yellow markings",
    "tomato_frog": "a tomato frog, a round plump frog in bright orange-red",
    "surinam_toad": "a Surinam toad, a very flat diamond-shaped brown toad with tiny star-shaped fingertips",
    "spadefoot_toad": "a spadefoot toad, a small plump brown toad with vertical pupils",
    "wood_frog": "a wood frog, a brown frog with a dark mask-like marking around each eye",
    "tiger_salamander": "a tiger salamander, a black salamander with bold yellow blotches along its body",
    "olm": "an olm, a pale pink eel-like salamander with no visible eyes and feathery external gills",
    "viperfish": "a viperfish, a slender dark deep-sea fish with long needle-thin teeth that protrude past its jaw",
    "snailfish": "a snailfish, a pale soft gelatinous tadpole-like fish with a translucent body",
    "yeti_crab": "a yeti crab, a pale white crab with long fuzzy bristles covering its claws",
    "tube_worm": "a cluster of tall white tube worms, each topped with a feathery red plume",
    "vampire_squid_giant": "a Humboldt squid, a large reddish squid with long tentacles lined with suckers and big eyes",
    "lions_mane_jellyfish": "a lion's mane jellyfish, with a reddish-orange bell and a mass of long thin trailing tentacles",
    "portuguese_man_of_war": "a Portuguese man o' war, a translucent blue-purple floating balloon-like creature trailing long thin blue tentacles",
    "mantis_shrimp_punching": "a boxer crab, a tiny crab holding a small pom-pom-like sea anemone in each claw",
    "pistol_shrimp": "a pistol shrimp, a small pale shrimp with one claw much larger than the other",
    "nudibranch_rainbow": "a rainbow nudibranch, a soft-bodied sea slug in vivid rainbow colors with frilly branching appendages on its back",
    "sand_dollar": "a sand dollar, a flat round white disc with a faint five-petal pattern on its surface",
    "sea_pig": "a sea pig, a small pink translucent sea cucumber with several stubby tube-like legs",
}
