"""
Opisy zwierząt po angielsku — wejście dla generatora grafik.

Baza trzyma tylko nazwy polskie, a model po polsku myli gatunki. Źródłem prawdy
jest tu POLSKA nazwa z `animals.ts`, nie `id` — kilka identyfikatorów wprowadza
w błąd:

  binturong_indo  -> „Niedźwiedź pszczelarz" to biruang, nie binturong
  asp             -> „Boleń" to ryba, nie żmija
  bison           -> „Żubr" to żubr europejski; bizon ma własne `bison_american`
  bird_eater      -> „Ptasznik" to pająk ptasznik
  basilisk        -> bazyliszek płatkogłowy (jaszczurka), nie stwór z mitów
  finch           -> „Zięba" to zięba zwyczajna, nie dowolna łuszczakowata
  hawk            -> „Jastrząb" to jastrząb gołębiarz, nie jakikolwiek myszołów
  isopod_giant    -> „Rajak głębinowy" to ten sam stonóg morski co `giant_isopod`
                     (ciekawostka w bazie mówi wprost „morski stonóg"), więc
                     opisy różnią się tylko barwą
  komodo_juvenile -> młody waran z Komodo; dorosły siedzi w `komodo`

Każdy opis dokłada 1–2 cechy rozpoznawcze, bo dziecko ma odróżnić gatunki,
a nie tylko zobaczyć „jakieś słodkie zwierzę".

Gdy branch `fix/animal-data` podmienił gatunek pod istniejącym `id` (np.
`axolotl_pink` z aksolotla na żabę moczarową), opis MUSI pójść za nową polską
nazwą — inaczej rysunek pokazuje co innego niż podpis.

Opisy owadów i pająków trzeba trzymać łagodnie: „army ant soldier with very
large curved jaws" i „brown recluse ... violin shape" odbiły się od filtru
bezpieczeństwa modelu. Wystarczyło opisać kształt zamiast nazywać groźny
gatunek — zwroty były bezpłatne, ale zadanie przepada.
"""

DESCRIPTIONS: dict[str, str] = {
    # --- partia 1 (wygenerowana) ---
    "aardvark": "an aardvark, with its long snout, long ears and arched back",
    "aardvark_pig": "a babirusa, a wild pig with sparse grey bristles and long curved tusks that grow upward through the snout",
    "aardwolf": "an aardwolf, a small striped hyena-like animal with a bushy mane and pointed ears",
    "aardwolf_kenya": "a striped hyena, grey-brown with black leg stripes, a long shaggy mane along the back and large pointed ears",
    "addax": "an addax antelope, white coat with a brown forehead patch and long spiral horns",
    "adelie_penguin": "an Adelie penguin, black head with a white ring around the eye",
    "african_wild_dog": "an African wild dog, with big round ears and a patchy brown, black and white coat",
    "agouti": "an agouti, a large rodent with a rounded body, slim legs and glossy brown fur",
    "albatross": "an albatross, a large white seabird with very long narrow wings and a hooked pale beak",
    "alligator": "an alligator, with a broad rounded snout and bumpy dark green scales",

    # --- partia 2 ---
    "alligator_snapping": "an alligator snapping turtle, with a spiky ridged shell and a strongly hooked beak",
    "alpaca": "an alpaca, with a woolly fleece, long neck and a shaggy fringe over the eyes",
    "amphipod_giant": "a giant amphipod, a pale shrimp-like crustacean with a curved segmented body",
    "anaconda": "a green anaconda, a very thick olive-green snake with dark oval blotches",
    "anchovy": "an anchovy, a small slender silver fish with a bright lateral stripe",
    "angelfish": "a freshwater angelfish, a tall flat triangular fish with long trailing fins and vertical stripes",
    "angler_fish": "a deep-sea anglerfish, dark round body, huge toothy mouth and a glowing lure on its head",
    "anole": "a green anole lizard, slender and bright green with a pink throat fan",
    "ant": "a black garden ant, with a narrow waist, six legs and bent antennae",
    "anteater": "a giant anteater, with a very long tube snout, bushy striped tail and a dark shoulder stripe",
    "antelope": "an impala antelope, sandy coat, white belly and long lyre-shaped horns",
    "aphid": "an aphid, a tiny pear-shaped green insect on a leaf",
    "arapaima": "an arapaima, a huge elongated river fish with large red-edged scales",
    "arctic_fox": "an arctic fox in white winter coat, with small rounded ears and a very bushy tail",
    "arctic_tern": "an arctic tern, a slim white seabird with a black cap, red beak and forked tail",
    "arctic_wolf": "an arctic wolf, thick white fur, broad head and amber eyes",
    "argali": "an argali wild sheep, with enormous curling horns and a pale neck ruff",
    "armadillo": "a nine-banded armadillo, with a segmented bony shell and a long thin tail",
    "army_ant": "a reddish-brown ant with a slender segmented body, bent antennae and six thin legs",
    "arowana": "an arowana, a long silver fish with big shining scales and two barbels on the chin",
    "asian_elephant": "an Asian elephant, smaller rounded ears, arched back and a domed head",
    "asian_hornet": "an Asian hornet, dark body with a yellow band and orange face",
    "asp": "an asp fish, a slim silvery predatory river fish with a pointed jutting lower jaw",
    "atlantic_puffin": "a razorbill, a black and white seabird with a deep blunt black beak crossed by a thin white line",
    "atlas_butterfly": "a Queen Alexandra's birdwing butterfly, very large with long narrow wings in iridescent blue-green and a bright yellow body",
    "atlas_moth": "a big friendly cartoon moth with soft furry body and wide patterned wings in warm brown and cream",
    "atolla_jellyfish": "an Atolla jellyfish, a deep red bell with many trailing tentacles and one long one",
    "avocet": "a pied avocet, white with black markings, long blue legs and a thin upcurved beak",
    "axolotl": "an axolotl, pale pink with feathery external gills and a wide smiling face",
    "axolotl_pink": "a moor frog, a small brown frog with a dark eye patch and a pale stripe down the back",
    "aye_aye": "an aye-aye, a lemur with huge round eyes, enormous ears and one very long thin finger",
    "badger": "a European badger, stocky grey body with bold black and white face stripes",
    "bald_eagle": "a bald eagle, white head and tail, dark brown body and a large yellow hooked beak",
    "bandicoot": "a bandicoot, a small marsupial with a pointed snout, big ears and coarse brown fur",
    "banteng": "a banteng, wild cattle with white stockings, a white rump patch and curved horns",
    "barn_owl": "a barn owl, with a white heart-shaped face and golden speckled wings",
    "barnacle": "a cluster of acorn barnacles, pale cone-shaped shells on a rock",
    "barracuda": "a barracuda, long silver torpedo-shaped fish with a jutting jaw and sharp teeth",
    "barreleye": "a barreleye fish, a small deep-sea fish with a transparent dome head and tubular green eyes",
    "basilisk": "a plumed basilisk lizard, bright green with a tall crest on head and back",
    "bat": "a small brown bat hanging, with wide membrane wings and big rounded ears",
    "beaded_lizard": "a Mexican beaded lizard, stout black body covered in yellow bead-like scales",
    "bearded_seal": "a bearded seal, plump grey body with very long white whiskers",
    "beaver": "a beaver, with a stocky brown body, orange front teeth and a flat scaly tail",
    "bee": "a honeybee, golden and black striped fuzzy body with translucent wings",
    "bee_eater": "a European bee-eater, turquoise belly, chestnut back, yellow throat and a long curved beak",
    "beetle": "a stag beetle, glossy dark brown with large antler-like jaws",
    "beluga": "a beluga whale, all white with a rounded forehead melon and no dorsal fin",
    "betta": "a betta fish, deep blue and red with huge flowing veil fins",
    "bharal": "a bharal blue sheep, blue-grey coat with black flank stripes and short curved horns",
    "bigfoot": "a friendly bigfoot, a tall shaggy brown ape-like creature with big feet",
    "bilby": "a bilby, a small marsupial with very long rabbit-like ears and a black-and-white tail",
    "binturong": "a binturong, a shaggy black bearcat with tufted ears and a long prehensile tail",
    "binturong_indo": "a masked palm civet, slender grey-brown with a bold white facial stripe from forehead to nose and a long tail",
    "bird_eater": "a Goliath birdeater tarantula, a very large hairy brown spider",
    "bird_of_paradise": "a bird of paradise, with brilliant yellow and orange plumes and long wire tail feathers",
    "bison": "a European bison, a massive brown wisent with a high shoulder hump and short curved horns",
    "bison_american": "an American bison, huge shaggy brown head and shoulders with a beard",
    "black_widow": "a black widow spider, glossy black with a red hourglass on the abdomen",
    "black_woodpecker": "a black woodpecker, all black with a bright red crown and pale eye",
    "blackbird": "a common blackbird, glossy black plumage with an orange-yellow beak and eye ring",
    "blobfish": "a blobfish, a pale pink gelatinous deep-sea fish with a droopy nose and sad face",
    "blue_crab": "a blue crab, with bright blue claws and a wide flattened olive shell",
    "blue_morpho": "a blue morpho butterfly with brilliant iridescent blue wings spread open",
    "blue_whale_pygmy": "a pygmy blue whale, a slender blue-grey whale with a small dorsal fin far back",
    "boa": "a boa constrictor, a thick tan snake with dark brown saddle-shaped markings",
    "bombardier_beetle": "a bombardier beetle, orange head and legs with a blue-black abdomen",
    "bongo": "a bongo antelope, chestnut red with bold white vertical stripes and spiral horns",
    "booby": "a blue-footed booby, a white and brown seabird with vivid bright blue feet",
    "bowerbird": "a satin bowerbird, glossy blue-black with violet eyes, beside a stick bower",
    "bowhead": "a bowhead whale, a stocky black whale with a huge arched jaw and white chin patch",
    "box_jellyfish": "a box jellyfish, a transparent cube-shaped bell with long trailing tentacles",
    "brachiosaurus": "a friendly brachiosaurus, a long-necked dinosaur with front legs longer than the back",
    "bream": "a common bream, a deep flat-bodied bronze fish with small head",
    "brittle_star": "a brittle star, with a small central disc and five long thin flexible arms",
    "brook_trout": "a huchen, a very large elongated salmon with a coppery-brown back and small dark spots",
    "brown_bear": "a brown bear, heavy build with a shoulder hump and small round ears",
    "brown_recluse": "a cute cartoon spider with a round light-brown body, big friendly eyes and eight slender legs",
    "budgerigar": "a budgerigar, a small green and yellow parrot with black barring and a blue cere",
    "buffalo": "an African buffalo, black with heavy horns joined in a boss across the forehead",
    "bull_shark": "a bull shark, stocky grey shark with a short blunt rounded snout",
    "bullfinch": "a Eurasian bullfinch, a plump bird with a rosy red breast, black cap and grey back",
    "bullfrog": "an American bullfrog, large olive-green frog with a big round eardrum",
    "bumblebee": "a bumblebee, very fuzzy round body with black and yellow bands",
    "burbot": "a burbot, a long mottled brown freshwater cod with a single chin barbel",
    "bush_dog": "a bush dog, small stocky reddish-brown wild dog with short legs and small ears",
    "bushmaster": "a bushmaster snake, large tan pit viper with dark diamond markings",
    "butterfly": "a butterfly with open patterned orange and black wings",
    "butterflyfish": "a butterflyfish, a round yellow and white reef fish with a black eye stripe",
    "buzzard": "a common buzzard, a broad-winged brown hawk with a pale chest band",
    "caecilian": "a caecilian, a legless burrowing amphibian that looks like a large smooth ringed worm",
    "caiman": "a spectacled caiman, olive-green with a bony ridge between the eyes",
    "camel_spider": "a camel spider, a pale tan solifuge with very large forward-facing jaws",
    "canary": "a canary, a small bright yellow songbird with a conical beak",
    "candiru": "a candiru, a tiny translucent pale catfish with a slender eel-like body",
    "cane_toad": "a cane toad, a very large warty brown toad with big poison glands behind the eyes",
    "capybara": "a capybara, the largest rodent, barrel-shaped with a blunt square muzzle",
    "caracal": "a caracal, a tawny wild cat with very long black ear tufts",
    "caribou": "a caribou reindeer, with broad branching antlers and a pale neck mane",
    "carp": "a common carp, a stocky golden-bronze fish with large scales and two pairs of barbels",

    # --- partia 3 ---
    "carpenter_ant": "a large black carpenter ant with a shiny segmented body and bent antennae",
    "cassowary": "a cassowary, a big flightless bird with a tall bony helmet, blue neck and red wattles",
    "cassowary_dwarf": "a dwarf cassowary, smaller with a low helmet and bright blue bare neck",
    "cat": "a domestic cat sitting, with upright ears, round eyes and a curled tail",
    "caterpillar": "a plump green caterpillar with soft segments and tiny legs on a leaf",
    "catfish": "a wels catfish, a long smooth dark fish with a wide flat head and long barbels",
    "catfish_polish": "a barbel fish, a slim golden-brown river fish with a rounded snout and four chin barbels",
    "centipede": "a centipede, a long flat reddish-brown body with many pairs of thin legs",
    "chameleon": "a chameleon, green with a curled tail, bulging swivel eyes and a crested head",
    "chamois": "a chamois, a goat-antelope with a pale face, black eye stripes and short hooked horns",
    "cheetah": "a cheetah, slender tan cat with solid round black spots and black tear lines down the face",
    "chicken": "a hen, plump brown body with a small red comb and wattles",
    "chimpanzee": "a chimpanzee sitting, dark fur with a pale face and big expressive ears",
    "chinchilla": "a chinchilla, very soft grey fur, round ears and a bushy tail",
    "chinstrap_penguin": "a chinstrap penguin, white face with a thin black line under the chin",
    "chipmunk": "a chipmunk, small striped rodent with bold dark and cream stripes along its back",
    "chub": "a chub, a stocky silver river fish with large scales and a broad blunt head",
    "cicada": "a cicada, a broad-headed insect with clear veined wings held roof-like over the body",
    "cicada_periodical": "a periodical cicada with a black body, bright red eyes and orange wing veins",
    "clam": "a clam with a pale ridged two-part shell, slightly open",
    "cleaner_shrimp": "a cleaner shrimp, translucent with bold red and white stripes and long white antennae",
    "clouded_leopard": "a clouded leopard, grey-gold cat with large cloud-shaped blotches and a very long tail",
    "clownfish": "a clownfish, bright orange with three white bands edged in black",
    "coati": "a coati, brown with a long upturned snout and a ringed tail held upright",
    "cobra": "a cobra rearing up with its hood spread wide",
    "cockatoo": "a sulphur-crested cockatoo, white with a bright yellow crest raised",
    "cockroach": "a cockroach, a flat oval glossy brown insect with long thin antennae",
    "cockroach_asian": "a slender light-brown roach with long antennae and pale wing covers",
    "coconut_crab": "a coconut crab, a huge land crab with thick blue-purple claws and sturdy legs",
    "cod": "an Atlantic cod, olive-brown speckled fish with a pale lateral line and a chin barbel",
    "coelacanth": "a coelacanth, a heavy blue fish with white flecks and thick lobed fins",
    "comb_jelly": "a comb jelly, a transparent oval jelly with shimmering rainbow comb rows",
    "condor": "an Andean condor, black with a white neck ruff and a bare pink head",
    "cone_snail": "a cone snail with a smooth glossy cone-shaped shell patterned in brown and cream",
    "copperhead": "a copperhead snake, coppery tan with darker hourglass bands",
    "coral": "a branching coral colony in warm orange and pink",
    "coral_snake": "a coral snake with bold red, yellow and black rings",
    "cormorant": "a cormorant standing with wings spread, glossy black with a hooked beak",
    "cow": "a dairy cow, white with black patches, a pink muzzle and a small udder",
    "coyote": "a coyote, slender grey-tan wild dog with large pointed ears and a bushy tail",
    "crab": "a crab with a rounded red shell, two big claws and stalked eyes",
    "crab_japanese_spider": "a Japanese spider crab with an orange body and extremely long thin legs",
    "crab_spider": "a crab spider, a small pale spider with wide front legs held sideways like a crab",
    "crane_grey": "a common crane, tall grey bird with a red crown patch and a white cheek stripe",
    "crayfish": "a crayfish, a small freshwater lobster with brown-red shell and raised claws",
    "crested_gecko": "a crested gecko, warm orange with fringed crests over the eyes and no eyelids",
    "cricket": "a cricket, a brown insect with long hind legs and very long thin antennae",
    "cricket_house": "a house cricket, pale straw-brown with dark head bands and long antennae",
    "crocodile": "a crocodile with a narrow V-shaped snout and visible teeth along the jawline",
    "crossbill": "a crossbill, a red finch whose beak tips cross over each other",
    "crow": "a crow, all black with a stout beak and glossy feathers",
    "crown_of_thorns_starfish": "a crown-of-thorns starfish, a large purple-red star covered in spines",
    "crowned_crane": "a grey crowned crane with a golden spray crest, white cheeks and a red throat pouch",
    "crucian": "a crucian carp, a deep-bodied golden-bronze fish with a rounded back",
    "cuckoo": "a common cuckoo, slim grey bird with a barred white belly and a long tail",
    "cuttlefish": "a cuttlefish with a broad flat body, W-shaped pupils and a fringe fin all around",
    "cuttlefish_giant": "a giant cuttlefish, large and iridescent with wavy arms and a wide fin fringe",
    "damselfly": "a damselfly, very slender with a bright blue body and wings folded along the back",
    "darwin_frog": "a Darwin's frog, small green-brown frog with a pointed nose like a leaf tip",
    "deathstalker": "a pale yellow scorpion with slender pincers and a thin curved tail",
    "deer": "a red deer stag, russet coat with tall branching antlers",
    "dhole": "a dhole, a reddish Asian wild dog with a bushy black-tipped tail and rounded ears",
    "dik_dik": "a dik-dik, a tiny antelope with huge dark eyes and a long flexible snout",
    "dingo": "a dingo, a sandy-ginger wild dog with erect ears and a bushy tail",
    "discus": "a discus fish, a very round flat fish with swirling blue and orange patterns",
    "dog": "a friendly dog sitting, with floppy ears and a wagging tail",
    "dolphin": "a bottlenose dolphin leaping, grey with a curved dorsal fin and a smiling beak",
    "donkey": "a donkey, grey with very long ears and a dark shoulder stripe",
    "dormouse": "an edible dormouse, soft grey fur, big black eyes and a bushy squirrel-like tail",
    "dormouse_garden": "a garden dormouse, brown above and white below with a black bandit mask",
    "dragon": "a friendly cartoon dragon, green scales, small wings and a curled tail",
    "dragonfish": "a deep-sea dragonfish, long dark eel-like body with a glowing barbel on the chin",
    "dragonfly": "a dragonfly with a slim iridescent blue body and four clear outstretched wings",
    "duck": "a mallard duck, green head, white neck ring and a yellow bill",
    "dugong": "a dugong, a plump grey sea cow with a broad downturned snout and a whale-like tail",
    "duiker": "a duiker, a small forest antelope with a rounded back and short straight horns",
    "dumbo_octopus": "a Dumbo octopus, pale pink with two big ear-like fins above the eyes",
    "dung_beetle": "a dung beetle, glossy black and round, rolling a small ball",
    "dungeness_crab": "a Dungeness crab with a wide purple-brown shell and pale-tipped claws",
    "eagle": "a golden eagle, dark brown with a golden nape and a large hooked beak",
    "eagle_owl": "a Eurasian eagle-owl, large tawny owl with orange eyes and prominent ear tufts",
    "eagle_owl_white": "a long-eared owl, slim grey-brown owl with very long ear tufts and orange eyes",
    "earthworm": "an earthworm, a smooth pink segmented worm with a pale band",
    "earwig": "an earwig, a slim brown insect with small pincers at the tail end",
    "echidna": "an echidna, a round spiny anteater with a long thin beak and cream spines",
    "eel": "a European eel, a long smooth snake-like fish with a continuous fin along the back",
    "eel_electric": "an electric eel, a long dark grey-brown fish with a flat head and orange throat",
    "eland": "a common eland, a very large tan antelope with a dewlap and straight spiral horns",
    "electric_ray": "an electric ray, a round flat brown ray with a short thick tail",
    "elephant": "an African elephant, very large ears, a long trunk and curved tusks",
    "elephant_seal": "an elephant seal, a huge grey seal with an inflatable trunk-like nose",
    "elk": "a moose, dark brown with a long drooping muzzle, a dewlap and broad flat antlers",
    "emperor_scorpion": "a large glossy black scorpion with thick pincers and a curved tail",
    "emu": "an emu, a tall shaggy brown flightless bird with a slim blue-grey neck",
    "european_hamster": "a European hamster, stocky with a black belly, white patches and small ears",
    "european_mink": "a European mink, sleek dark brown with a white chin and upper lip",
    "fairy_wren": "a superb fairywren, a tiny bird with a brilliant blue cap and cheeks and a cocked tail",
    "falcon": "a peregrine falcon, slate-grey back, barred white chest and a dark moustache mark",
    "feather_star": "a feather star, a crinoid with many feathery orange arms spread out",
    "fennec": "a fennec fox, tiny pale sandy fox with enormous ears",
    # --- partia 4 ---
    "ferret": "a domestic ferret, long slender cream body with a dark bandit mask and dark feet",
    "field_mouse": "a wood mouse, sandy-brown with a white belly, huge round ears and a long thin tail",
    "finch": "a common chaffinch, a small bird with a blue-grey cap, pinkish cheeks and two white wing bars",
    "fire_belly_toad": "an oriental fire-bellied toad, bumpy green and black back with a bright orange-and-black belly",
    "fire_salamander": "a fire salamander, glossy black with bold yellow blotches and a rounded head",
    "firefly": "a firefly beetle, a small brown beetle with a soft glowing yellow-green tip on its abdomen",
    "fishing_cat": "a fishing cat, a stocky olive-grey wild cat with dark spots in rows and a short thick tail",
    "flamingo": "a greater flamingo, tall pink bird on one leg with a long curved neck and a black-tipped bent bill",
    "flatworm": "a marine flatworm, a flat ribbon-like creature with ruffled edges and bright orange and blue stripes",
    "flea": "a flea, a tiny rounded brown insect with a smooth arched shell and long springy back legs",
    "flounder": "a flounder, a flat oval fish lying sideways with both eyes on one speckled brown side",
    "fly": "a housefly, a small grey insect with big round red eyes and two clear wings",
    "flying_fish": "a flying fish, a slim silvery fish with enormous wing-like pectoral fins spread out",
    "flying_squirrel": "a flying squirrel, grey-brown with huge black eyes and a skin flap stretched between its legs",
    "fossa": "a fossa, a slender rust-brown cat-like animal from Madagascar with a very long tail and a short muzzle",
    "fox": "a red fox, orange-red fur with a white chest, black legs and a bushy white-tipped tail",
    "frigatebird": "a great frigatebird, a black seabird with long pointed wings, a forked tail and a red throat pouch",
    "frilled_lizard": "a frilled lizard, sandy-brown with a wide round collar of skin fanned out around its head",
    "frog": "a common frog, a plump green-brown frog with golden eyes and long folded back legs",
    "frogfish": "a frogfish, a round lumpy yellow-orange fish with a tiny fishing rod on its forehead and leg-like fins",
    "funnel_web_spider": "a cute cartoon spider with a round glossy dark body, short sturdy legs and a small shiny head",
    "gaboon_viper": "a Gaboon viper, a thick short snake with a broad triangular head and a beautiful leaf-pattern of tan, brown and cream",
    "galago": "a bushbaby, a tiny grey primate with enormous round eyes, big thin ears and a long fluffy tail",
    "galapagos_tortoise": "a Galapagos giant tortoise, a huge domed grey shell, thick elephant-like legs and a long wrinkled neck",
    "gannet": "a northern gannet, a white seabird with a golden-buff head, black wingtips and a long pointed blue-grey bill",
    "garter_snake": "a garter snake, a slim smooth snake with three yellow stripes running along a dark olive body",
    "gaur": "a gaur, a massive dark brown wild ox with white stockings and a high ridge along its shoulders",
    "gazelle": "a Thomson's gazelle, tan with a bold black side stripe, white belly and slender ringed horns",
    "gecko": "a leopard gecko, a plump yellow lizard with black spots, a fat banded tail and a smiling face",
    "genet": "a common genet, a slender spotted grey cat-like animal with a very long black-and-white ringed tail",
    "gentoo_penguin": "a gentoo penguin, black and white with a wide white bonnet stripe over the eyes and an orange bill",
    "gerbil": "a Mongolian gerbil, sandy-brown with a white belly, large dark eyes and a tufted tail tip",
    "gharial": "a gharial, a slim crocodile with a very long narrow snout and a round bulb on the tip",
    "ghost_shark": "a chimaera or ghost shark, a pale silvery fish with huge green eyes, smooth skin and a long thin tail",
    "giant_anteater": "a tamandua, a small tree anteater with a golden coat and a bold black vest marking over the shoulders",
    "giant_centipede": "a giant centipede, a long reddish segmented body with many small orange legs along each side",
    "giant_isopod": "a giant isopod, a pale cream armoured sea bug with overlapping plates and large dark eyes",
    "giant_otter": "a giant otter, a long chocolate-brown otter with a cream throat patch and a wide flat paddle tail",
    "giant_salamander": "a giant salamander, a large flat wrinkled brown amphibian with tiny eyes and a broad rounded head",
    "giant_squid": "a giant squid, a long pale pink torpedo body with two huge eyes, eight arms and two longer tentacles",
    "giant_weta": "a giant weta, a large plump brown cricket-like insect with long antennae and thick spiny back legs",
    "gibbon": "a gibbon, a slim black-and-cream ape with extremely long arms and a pale face ring",
    "gila_monster": "a Gila monster, a chunky lizard with bumpy bead-like black and orange-pink skin and a fat tail",
    "giraffe": "a giraffe, a very long neck, tan coat with brown patches and two small furry horns",
    "glass_frog": "a glass frog, a tiny lime-green frog with see-through belly skin and big round eyes",
    "glass_octopus": "a glass octopus, an almost transparent octopus with visible tube-shaped eyes and thin clear arms",
    "gnu": "a blue wildebeest, a slate-grey ox-like antelope with a shaggy beard, curved horns and a dark mane",
    "goat": "a domestic goat, white with a short beard, backward-curving horns and rectangular pupils",
    "goblin_shark": "a goblin shark, a pale pink shark with a long flat blade-shaped snout and a slim body",
    "goldcrest": "a goldcrest, a tiny olive-green bird with a bright yellow crown stripe and a plump round body",
    "goldfinch": "a European goldfinch, a small bird with a red face, black-and-white head and a broad yellow wing bar",
    "goliath_beetle": "a Goliath beetle, a very large beetle with bold black-and-white striped back plates and reddish wing cases",
    "goose": "a greylag goose, a grey-brown goose with an orange bill and pink legs",
    "gorilla": "a mountain gorilla, a big black ape with a broad chest, a domed head and a silver-grey back",
    "gourami": "a pearl gourami, a flat oval fish with a pearly spotted body and very long thin feeler fins",
    "grass_snake": "a grass snake, a slim olive-green snake with a yellow-and-black collar behind the head",
    "grasshopper": "a grasshopper, a slim green insect with long folded jumping legs and short antennae",
    "gray_whale": "a gray whale, a mottled grey whale with a knobbly back ridge instead of a fin and pale barnacle patches",
    "grayling": "a grayling fish, a silvery fish with a very tall sail-like dorsal fin and a small pointed head",
    "great_grey_owl": "a great grey owl, a large grey owl with a huge round face of grey rings and small yellow eyes",
    "great_tit": "a great tit, a small bird with a black head, white cheeks, yellow breast and a black belly stripe",
    "great_white": "a great white shark, a grey torpedo-shaped shark with a white belly, a pointed snout and a tall triangular fin",
    "grebe": "a little grebe, a small round brown water bird with a chestnut neck and a fluffy tail-less rear",
    "grebe_great": "a great crested grebe, a slim white-necked water bird with a black crest and chestnut ruffs on the cheeks",
    "green_anaconda": "an emerald tree boa, bright green with white zigzag bars, coiled in loops over a branch",
    "griffin": "a friendly cartoon griffin, an eagle head and wings on a golden lion body with a tufted tail",
    "grizzly": "a grizzly bear, a big brown bear with a humped shoulder, a dished face and thick shaggy fur",
    "grouper": "a grouper, a big-bodied fish with a large mouth, thick lips and a mottled brown and pale pattern",
    "guanaco": "a guanaco, a slim tan llama-like animal with a grey face, white belly and large pointed ears",
    "guinea_fowl": "a helmeted guineafowl, a round dark grey bird covered in white dots with a bare blue head and a bony helmet",
    "guinea_pig": "a guinea pig, a plump tailless rodent with short legs and a brown-and-white patchy coat",
    "gulper_eel": "a gulper eel, a dark eel with an enormous pouch-like mouth and a very thin whip tail",
    "guppy": "a guppy, a tiny fish with a silver body and a large colourful orange and blue fan tail",
    "hagfish": "a hagfish, a long smooth grey-pink eel-like fish with no jaws and short barbels around the mouth",
    "halibut": "a halibut, a very large flat diamond-shaped fish with both eyes on its dark brown upper side",
    "hammerhead": "a hammerhead shark, a grey shark with a wide flat hammer-shaped head and an eye at each end",
    "hamster": "a Syrian hamster, a round golden-brown rodent with puffed cheek pouches and tiny ears",
    "hare": "a brown hare, long black-tipped ears, long powerful back legs and a lean tawny body",
    "harpy_eagle": "a harpy eagle, a big grey-and-white eagle with a black chest band and a crown of raised feathers",
    "harvestman": "a harvestman, a cute cartoon creature with one small round body and eight very long thin legs",
    "hawfinch": "a hawfinch, a stocky orange-brown finch with a huge silver-grey conical bill and a short white-tipped tail",
    "hawk": "a northern goshawk, a grey-backed hawk with finely barred white underparts and a bold white eyebrow stripe",
    "hawksbill_turtle": "a hawksbill sea turtle, an amber shell with overlapping patterned plates and a narrow pointed beak",
    "hedgehog": "a hedgehog, a round animal covered in brown-and-cream spines with a small pointed brown face",
    "hellbender": "a hellbender salamander, a big flat wrinkled brown amphibian with frilly skin folds along its sides",
    "hercules_beetle": "a Hercules beetle, a large beetle with olive-yellow wing cases and one long curved horn above its head",
    "hermit_crab": "a hermit crab, a small crab peeking out of a spiral seashell with one bigger orange claw",
    "heron": "a grey heron, a tall grey wading bird with a long S-shaped neck, a dagger bill and a black head plume",
    "herring": "a herring, a slim silvery-blue fish with a deeply forked tail and large round scales",
    "herring_gull": "a herring gull, a white gull with pale grey wings, black wingtips and a yellow bill with a red spot",
    "hippo": "a hippopotamus, a huge barrel-shaped grey animal with a very wide mouth and tiny ears",
    "hoatzin": "a hoatzin, a brown bird with a spiky ragged crest, a bare blue face and red eyes",
    "hobby": "a Eurasian hobby, a small slim falcon with a dark moustache mark, streaked chest and rusty-red trousers",
    "honey_badger": "a zorilla, a small striped polecat, black with four bold white stripes along the back and a bushy tail",
    "honey_possum": "a honey possum, a tiny brown mouse-like marsupial with three dark back stripes and a long pointed snout",
    "honeypot_ant": "a honeypot ant, a reddish-brown ant with a slender segmented body and a big round amber abdomen",
    "hoopoe": "a hoopoe, a sandy-pink bird with a tall fan-shaped orange crest and black-and-white striped wings",
    "hornbill": "a great hornbill, a big black-and-white bird with a huge curved yellow bill topped by a casque",
    "horned_lizard": "a horned lizard, a flat round sandy lizard with a crown of small blunt spikes around its head",
    "hornet": "a European hornet, a large gentle wasp with a brown-and-yellow striped body and clear wings",
    "horse": "a horse, a chestnut-brown horse with a flowing dark mane and tail and white socks",
    "horseshoe_crab": "a horseshoe crab, a smooth brown helmet-shaped shell with a long straight spike tail",
    "hummingbird": "a ruby-throated hummingbird, a tiny emerald-green bird with a red throat and a long thin bill, wings blurred",
    "humpback": "a humpback whale, a dark whale with very long white flippers and a knobbly bumpy head",
    "huntsman_spider": "a cute cartoon spider with a flat light-brown body and long sideways-spread legs, friendly and round-eyed",
    "hyena": "a spotted hyena, a sandy coat with dark round spots, a sloping back and large rounded ears",
    "ibex": "an Alpine ibex, a sturdy grey-brown mountain goat with enormous ridged curved-back horns",
    "ibis": "a sacred ibis, a white bird with a bare black head and neck and a long curved black bill",
    "iguana": "a green iguana, a bright green lizard with a spiny crest along its back and a round cheek scale",
    "impala": "an impala, a slender reddish antelope with a white belly, black rump stripes and long lyre-shaped horns",
    "indri": "an indri, a black-and-white lemur with a round green-eyed face, tufted ears and almost no tail",
    "isopod_giant": "a common woodlouse, a small grey segmented land crustacean with many short legs",
    "jackal": "a golden jackal, a slim sandy-gold wild dog with pointed ears and a black-tipped bushy tail",
    "jackdaw": "a jackdaw, a small black crow with a silver-grey nape and pale blue-white eyes",
    "jackson_chameleon": "a Jackson's chameleon, a green chameleon with three forward-pointing horns and curled tail",
    "jaguar": "a jaguar, a stocky golden cat with large rosette spots that have dots inside and a broad heavy head",
    "jaguarundi": "a jaguarundi, a small plain grey-brown cat with a long low body, short legs and a very long tail",
    "japanese_macaque": "a Japanese macaque, a thick grey-brown furred monkey with a bright red bare face and a short tail",
    "jay": "a Eurasian jay, a pinkish-brown bird with a bright blue barred wing patch and a black moustache stripe",
    "jellyfish": "a moon jellyfish, a translucent pale blue bell with four ring shapes inside and thin trailing tentacles",
    "jewel_beetle": "a jewel beetle, a torpedo-shaped beetle with shining metallic green wing cases and copper stripes",
    "jewel_beetle_emerald": "an emerald jewel beetle, a rounded beetle glowing bright emerald green with golden edges",
    "jumping_spider": "a cute cartoon jumping spider with a fuzzy round body and two very large friendly front eyes",
    "kakapo": "a kakapo, a big round moss-green parrot with mottled feathers, an owl-like face disc and a pale bill",
    "kangaroo": "a red kangaroo, a reddish-brown kangaroo with huge back legs, small arms and a thick tapered tail",
    "kea": "a kea, an olive-green mountain parrot with orange under its wings and a long curved grey bill",
    "kestrel": "a common kestrel, a small falcon with a rusty-red spotted back, grey head and a black-banded tail",
    "king_cobra": "a king cobra, an olive-brown snake rearing up with a narrow hood spread behind its head",
    "king_crab": "a red king crab, a spiny orange-red crab with a bumpy triangular shell and very long thin legs",
    "king_penguin": "a king penguin, black and white with bright orange teardrop ear patches and an orange bill stripe",
    "kingfisher": "a common kingfisher, a tiny bird with a brilliant blue back, orange chest and a long straight black bill",
    "kiwi": "a kiwi, a round shaggy brown flightless bird with no visible wings and a very long pale bill",
    "klipspringer": "a klipspringer, a small olive-speckled antelope standing on tiptoe hooves with short spike horns",
    "koala": "a koala, a grey round bear-like animal with huge fluffy ears and a large black spoon-shaped nose",
    "koi": "a koi carp, a plump fish with bold white, orange and black patches and flowing fins",
    "komodo": "a Komodo dragon, a very large grey-brown lizard with loose scaly skin, a long tail and sturdy legs",
    "komodo_juvenile": "a water monitor lizard, dark grey-brown with rows of pale yellow spots and a long banded tail",
    "kookaburra": "a laughing kookaburra, a chunky brown-and-cream kingfisher with a dark eye stripe and a huge bill",
    "kraken": "a friendly cartoon kraken, a big purple sea monster with curling tentacles and large round eyes",
    "krill": "a krill, a tiny transparent pink shrimp-like creature with big black eyes and feathery legs",
    "kudu": "a greater kudu, a grey-brown antelope with thin white side stripes and long corkscrew horns",
    "lacewing": "a green lacewing, a delicate pale green insect with golden eyes and large transparent net-veined wings",
    "ladybug": "a ladybird beetle, a round red beetle with seven black dots and a small black-and-white head",
    "langouste": "a spiny lobster, a reddish-brown lobster with no big claws, a spiny shell and very long thick antennae",
    "langur": "a grey langur, a slim monkey with silver-grey fur, a black face and a very long arching tail",
    "lanternfish": "a lanternfish, a small silvery-blue deep-sea fish with rows of tiny glowing dots along its belly",
    "lark": "a skylark, a streaky brown bird with a small pointed crest and white outer tail feathers",
    "leafcutter_ant": "a leafcutter ant, a reddish-brown ant with a slender segmented body carrying a green leaf piece",
    "leatherback_turtle": "a leatherback sea turtle, a huge dark rubbery shell with seven long ridges and very long front flippers",
    "lemming": "a Norway lemming, a small plump rodent with bold black, orange and cream patched fur and tiny ears",
}
